/**
 * The EDITORIAL half of the API surface inventory (issue #1242, D4).
 *
 * app/lib/api-surface-generated.ts carries everything the code states for
 * itself — paths, modules, methods, enforced capabilities, and the auth class
 * wherever an authoritative strategy fixes it. What is left here is what no
 * analyser can read off a handler: what a surface is FOR, which guide
 * documents it, how its body is encoded, and the prose an integrator needs.
 *
 * Keyed by `routeModule`, which is unique per entry and survives path edits.
 * The two halves are merged by app/lib/api-surface.ts and cross-checked by
 * `npm run tools:api:surface:check`: a generated route with no annotation
 * fails, and so does an annotation whose route no longer exists.
 *
 * `authClass` appears here ONLY for routes whose auth the generator could not
 * determine — a hand-rolled preamble, or a base helper like requireJsonAuth
 * that a deeper service-layer role gate may narrow. It is a declaration the
 * gate constrains, never an override: where an authoritative strategy fixes
 * the class, setting it here is a hard failure. Each one that disappears is a
 * route that grew a self-describing strategy.
 */
import type { ApiSurfaceAnnotation } from "@/lib/api-surface-types";

export const API_SURFACE_ANNOTATIONS: Readonly<
  Record<string, ApiSurfaceAnnotation>
> = {
  "app/routes/api+/agent-status.tsx": { ownerArea: "workspace", exposure: "sessionOnly", docsGuide: "docs/api-workspace-admin.md", bodyType: "json", authClass: "workspaceAdmin", workspaceScoped: true, notes: "Agent presence for workspace dialer sessions." },
  "app/routes/api+/audience-upload-status.tsx": { ownerArea: "audiences", exposure: "sessionOnly", docsGuide: "docs/api-data-management.md", authClass: "session", notes: "Poll audience CSV upload job status." },
  "app/routes/api+/audience-upload.tsx": { ownerArea: "audiences", exposure: "sessionOnly", docsGuide: "docs/api-data-management.md", bodyType: "multipart", authClass: "session", notes: "Upload audience CSV with column mapping." },
  "app/routes/api+/audio-upload.tsx": { ownerArea: "media", exposure: "sessionOnly", docsGuide: "docs/api-data-management.md", bodyType: "multipart", authClass: "session", notes: "Inline workspace audio upload from the script editor; normalizes to canonical MP3." },
  "app/routes/api+/audiences.tsx": { ownerArea: "audiences", exposure: "sessionOnly", docsGuide: "docs/api-data-management.md", bodyType: "form", authClass: "session", workspaceScoped: true },
  "app/routes/api+/audiodrop.tsx": { ownerArea: "telephony", exposure: "sessionOnly", docsGuide: "docs/api-telephony-control.md", bodyType: "form", authClass: "session", notes: "Voicemail drop during live call." },
  "app/routes/api+/auth/callback.route.tsx": { ownerArea: "auth", exposure: "publicUnauthenticated", docsGuide: "docs/api-auth-matrix.md", authClass: "publicForm", specTarget: "publicOpenApi", notes: "Postgres auth callback; sets session cookies and redirects." },
  "app/routes/api+/auto-dial/$roomId.route.tsx": { ownerArea: "dialer", exposure: "providerOnly", docsGuide: "docs/api-webhooks.md", bodyType: "form", notes: "Twilio conference/AMD TwiML callback." },
  "app/routes/api+/auto-dial/end.route.tsx": { ownerArea: "dialer", exposure: "sessionOnly", docsGuide: "docs/api-telephony-control.md", bodyType: "json", authClass: "session" },
  "app/routes/api+/auto-dial/status.route.tsx": { ownerArea: "dialer", exposure: "providerOnly", docsGuide: "docs/api-webhooks.md", bodyType: "form" },
  "app/routes/api+/call-status-poll.tsx": { ownerArea: "telephony", exposure: "sessionOnly", docsGuide: "docs/api-analytics-export.md", authClass: "session", workspaceScoped: true, notes: "Poll Twilio call status for call-screen UI." },
  "app/routes/api+/call-status.tsx": { ownerArea: "telephony", exposure: "providerOnly", docsGuide: "docs/api-webhooks.md", bodyType: "form" },
  "app/routes/api+/call.tsx": { ownerArea: "handset", exposure: "internalOnly", docsGuide: "docs/api-internal-unsupported.md", bodyType: "form", notes: "Twilio Voice URL for the handset bridge; the auth strategy validates the workspace Twilio signature and the handset session is looked up from the signed form fields. Returns TwiML." },
  "app/routes/api+/caller-id.tsx": { ownerArea: "telephony", exposure: "sessionOnly", docsGuide: "docs/api-telephony-control.md", bodyType: "json", authClass: "session", workspaceScoped: true, notes: "Start outbound caller-ID verification." },
  "app/routes/api+/caller-id/status.route.tsx": { ownerArea: "telephony", exposure: "providerOnly", docsGuide: "docs/api-webhooks.md", bodyType: "form" },
  "app/routes/api+/campaign-export-status.tsx": { ownerArea: "analytics", exposure: "sessionOnly", docsGuide: "docs/api-analytics-export.md", authClass: "session", workspaceScoped: true },
  "app/routes/api+/campaign-export.tsx": { ownerArea: "analytics", exposure: "sessionOnly", docsGuide: "docs/api-analytics-export.md", bodyType: "form", authClass: "session", workspaceScoped: true },
  "app/routes/api+/campaign_audience.tsx": { ownerArea: "campaigns", exposure: "sessionOnly", docsGuide: "docs/api-data-management.md", bodyType: "json", authClass: "session" },
  "app/routes/api+/campaign_queue.tsx": { ownerArea: "queues", exposure: "sessionOnly", docsGuide: "docs/api-telephony-control.md", bodyType: "form", authClass: "session" },
  "app/routes/api+/campaigns.tsx": { ownerArea: "campaigns", exposure: "sessionOnly", docsGuide: "docs/api-data-management.md", bodyType: "form", authClass: "session" },
  "app/routes/api+/coaching-ack.tsx": { ownerArea: "telephony", exposure: "sessionOnly", docsGuide: "docs/api-telephony-control.md", bodyType: "json", authClass: "session", workspaceScoped: true },
  "app/routes/api+/campaigns/create-with-script.route.tsx": { ownerArea: "campaigns", exposure: "publicSdk", docsGuide: "docs/api-create-campaign-with-script.md", bodyType: "json", authClass: "apiKeyOrSession", workspaceScoped: true },
  "app/routes/api+/chat_sms.tsx": { ownerArea: "messaging", exposure: "publicSdk", docsGuide: "docs/api-send-sms.md", bodyType: "json", authClass: "apiKeyOrSession", workspaceScoped: true },
  "app/routes/api+/connect-campaign-conference/$workspaceId/$campaignId.route.tsx": { ownerArea: "dialer", exposure: "providerOnly", docsGuide: "docs/api-webhooks.md", authClass: "twilioSignature", notes: "Twilio voice URL after connect-phone-device; returns TwiML." },
  "app/routes/api+/connect-phone-device.tsx": { ownerArea: "dialer", exposure: "sessionOnly", docsGuide: "docs/api-telephony-control.md", bodyType: "json", authClass: "session", workspaceScoped: true },
  "app/routes/api+/contact-audience.tsx": { ownerArea: "contacts", exposure: "sessionOnly", docsGuide: "docs/api-data-management.md", bodyType: "form", authClass: "session" },
  "app/routes/api+/contact-audience/bulk-delete.route.tsx": { ownerArea: "contacts", exposure: "sessionOnly", docsGuide: "docs/api-data-management.md", bodyType: "form", authClass: "session" },
  "app/routes/api+/contact-form.tsx": { ownerArea: "misc", exposure: "publicUnauthenticated", docsGuide: "docs/api-internal-unsupported.md", bodyType: "form", authClass: "publicForm", specTarget: "publicOpenApi", notes: "Marketing contact form; sends email via Resend." },
  "app/routes/api+/contacts.tsx": { ownerArea: "contacts", exposure: "sessionOnly", docsGuide: "docs/api-data-management.md", bodyType: "form", authClass: "session" },
  "app/routes/api+/dial.tsx": { ownerArea: "telephony", exposure: "sessionOnly", docsGuide: "docs/api-telephony-control.md", bodyType: "form", authClass: "session", workspaceScoped: true, notes: "Campaign dial initiation; returns TwiML." },
  "app/routes/api+/dial/$number.route.tsx": { ownerArea: "telephony", exposure: "providerOnly", docsGuide: "docs/api-webhooks.md", bodyType: "form", notes: "Twilio TwiML sub-route; requires a valid Twilio signature. Returns TwiML." },
  "app/routes/api+/dial/status.route.tsx": { ownerArea: "telephony", exposure: "providerOnly", docsGuide: "docs/api-webhooks.md", bodyType: "form" },
  "app/routes/api+/docs/openapi.route.tsx": { ownerArea: "docs", exposure: "publicUnauthenticated", docsGuide: "docs/api-overview.md", authClass: "publicForm", specTarget: "inventoryOnly", supported: true, notes: "Public user-facing OpenAPI JSON (session + workspace + integrator routes)." },
  "app/routes/api+/docs/openapi/all.route.tsx": { ownerArea: "docs", exposure: "publicUnauthenticated", docsGuide: "docs/api-overview.md", authClass: "publicForm", specTarget: "inventoryOnly", notes: "Complete classified API surface OpenAPI JSON." },
  "app/routes/api+/email-vm.tsx": { ownerArea: "telephony", exposure: "providerOnly", docsGuide: "docs/api-webhooks.md", bodyType: "form" },
  "app/routes/api+/error-report.tsx": { ownerArea: "misc", exposure: "sessionOnly", docsGuide: "docs/api-internal-unsupported.md", bodyType: "json", authClass: "session" },
  "app/routes/api+/handset-token.tsx": { ownerArea: "handset", exposure: "sessionOnly", docsGuide: "docs/api-telephony-control.md", authClass: "session", workspaceScoped: true },
  "app/routes/api+/hangup.tsx": { ownerArea: "telephony", exposure: "sessionOnly", docsGuide: "docs/api-telephony-control.md", bodyType: "form", authClass: "session", workspaceScoped: true },
  "app/routes/api+/inbound-handset-dial-end.tsx": { ownerArea: "handset", exposure: "providerOnly", docsGuide: "docs/api-webhooks.md", bodyType: "form" },
  "app/routes/api+/inbound-handset.tsx": { ownerArea: "handset", exposure: "providerOnly", docsGuide: "docs/api-webhooks.md", bodyType: "form" },
  "app/routes/api+/inbound-ivr/$numberId/$pageId.route.tsx": { ownerArea: "ivr", exposure: "providerOnly", docsGuide: "docs/api-webhooks.md", bodyType: "form", notes: "Returns TwiML." },
  "app/routes/api+/inbound-ivr/$numberId/$pageId/$blockId.route.tsx": { ownerArea: "ivr", exposure: "providerOnly", docsGuide: "docs/api-webhooks.md", bodyType: "form" },
  "app/routes/api+/inbound-ivr/$numberId/$pageId/$blockId/response.route.tsx": { ownerArea: "ivr", exposure: "providerOnly", docsGuide: "docs/api-webhooks.md", bodyType: "form" },
  "app/routes/api+/inbound-queue.tsx": { ownerArea: "inbound", exposure: "sessionOnly", docsGuide: "docs/api-telephony-control.md", bodyType: "json", authClass: "session", workspaceScoped: true },
  "app/routes/api+/inbound-sms.tsx": { ownerArea: "messaging", exposure: "providerOnly", docsGuide: "docs/api-webhooks.md", bodyType: "form" },
  "app/routes/api+/inbound-verification.tsx": { ownerArea: "inbound", exposure: "internalOnly", docsGuide: "docs/api-internal-unsupported.md", bodyType: "form", notes: "Call-in verification TwiML, authenticated by a main-account Twilio signature. Returns TwiML." },
  "app/routes/api+/inbound.tsx": { ownerArea: "inbound", exposure: "providerOnly", docsGuide: "docs/api-webhooks.md", bodyType: "form", notes: "Returns TwiML." },
  "app/routes/api+/jobs+/low-credit-notify.tsx": { ownerArea: "billing", exposure: "internalOnly", docsGuide: "docs/api-internal-unsupported.md", bodyType: "json", authClass: "internalTrusted", notes: "Cron-triggered low-credit email sweep; authenticated via x-cron-secret header (process.env.CRON_SECRET)." },
  "app/routes/api+/jobs+/number-rental-billing.tsx": { ownerArea: "billing", exposure: "internalOnly", docsGuide: "docs/api-internal-unsupported.md", bodyType: "json", authClass: "internalTrusted", notes: "Cron-triggered monthly number-rental billing; authenticated via x-cron-secret header (process.env.CRON_SECRET)." },
  "app/routes/api+/jobs+/billing-reconcile.tsx": { ownerArea: "billing", exposure: "internalOnly", docsGuide: "docs/api-internal-unsupported.md", bodyType: "json", authClass: "internalTrusted", notes: "Cron-triggered billing reconciliation snapshot; authenticated via x-cron-secret header (process.env.CRON_SECRET)." },
  "app/routes/api+/jobs+/twilio-open-sync.tsx": { ownerArea: "telephony", exposure: "internalOnly", docsGuide: "docs/api-internal-unsupported.md", bodyType: "json", authClass: "internalTrusted", notes: "Cron-triggered sync of open Twilio calls/messages; authenticated via x-cron-secret header (process.env.CRON_SECRET)." },
  "app/routes/api+/initiate-ivr.tsx": { ownerArea: "ivr", exposure: "sessionOnly", docsGuide: "docs/api-telephony-control.md", bodyType: "json", authClass: "session", workspaceScoped: true },
  "app/routes/api+/ivr.tsx": { ownerArea: "ivr", exposure: "sessionOnly", docsGuide: "docs/api-telephony-control.md", bodyType: "form", authClass: "session", workspaceScoped: true },
  "app/routes/api+/ivr/status.route.tsx": { ownerArea: "ivr", exposure: "providerOnly", docsGuide: "docs/api-webhooks.md", bodyType: "form" },
  "app/routes/api+/ivr/$campaignId/$pageId.route.tsx": { ownerArea: "ivr", exposure: "providerOnly", docsGuide: "docs/api-webhooks.md", bodyType: "form", notes: "Returns TwiML." },
  "app/routes/api+/ivr/$campaignId/$pageId/$blockId.route.tsx": { ownerArea: "ivr", exposure: "providerOnly", docsGuide: "docs/api-webhooks.md", bodyType: "form" },
  "app/routes/api+/ivr/$campaignId/$pageId/$blockId/response.route.tsx": { ownerArea: "ivr", exposure: "providerOnly", docsGuide: "docs/api-webhooks.md", bodyType: "form" },
  "app/routes/api+/media.tsx": { ownerArea: "media", exposure: "sessionOnly", docsGuide: "docs/api-data-management.md", bodyType: "multipart", authClass: "session" },
  "app/routes/api+/message_media.tsx": { ownerArea: "messaging", exposure: "sessionOnly", docsGuide: "docs/api-data-management.md", bodyTypeByMethod: { POST: "multipart", DELETE: "form" }, authClass: "session" },
  "app/routes/api+/numbers.tsx": { ownerArea: "telephony", exposure: "sessionOnly", docsGuide: "docs/api-workspace-admin.md", bodyType: "form", authClass: "session", workspaceScoped: true, notes: "Flat alias for /api/workspaces/:workspaceId/numbers used by the number purchase wizard. POST requires the member role or above; the caller role receives 403." },
  "app/routes/api+/outreach-attempts.tsx": { ownerArea: "campaigns", exposure: "sessionOnly", docsGuide: "docs/api-telephony-control.md", bodyType: "json", authClass: "session", notes: "Hyphenated path; preferred outreach attempt API." },
  "app/routes/api+/outreach_attempts/$id.route.tsx": { ownerArea: "campaigns", exposure: "internalOnly", docsGuide: "docs/api-internal-unsupported.md", bodyType: "json", authClass: "session", notes: "Session-scoped outreach attempt updates via requireJsonAuthForOutreachAttempt." },
  "app/routes/api+/questions.tsx": { ownerArea: "campaigns", exposure: "sessionOnly", docsGuide: "docs/api-telephony-control.md", bodyType: "json", authClass: "session", workspaceScoped: true, notes: "Call disposition / survey question updates on call screen." },
  "app/routes/api+/queues.tsx": { ownerArea: "queues", exposure: "sessionOnly", docsGuide: "docs/api-telephony-control.md", bodyType: "json", authClass: "session", notes: "Campaign queue dequeue and reset; requires session auth and workspace access." },
  "app/routes/api+/recording.tsx": { ownerArea: "telephony", exposure: "providerOnly", docsGuide: "docs/api-webhooks.md", bodyType: "form" },
  "app/routes/api+/reset_campaign.tsx": { ownerArea: "campaigns", exposure: "sessionOnly", docsGuide: "docs/api-data-management.md", bodyType: "form", authClass: "session" },
  "app/routes/api+/scripts.tsx": { ownerArea: "scripts", exposure: "sessionOnly", docsGuide: "docs/api-data-management.md", bodyType: "json", authClass: "session" },
  "app/routes/api+/sms.tsx": { ownerArea: "messaging", exposure: "publicSdk", docsGuide: "docs/api-send-sms.md", bodyType: "json", authClass: "apiKeyOrSession", workspaceScoped: true },
  "app/routes/api+/sms/status.route.tsx": { ownerArea: "messaging", exposure: "providerOnly", docsGuide: "docs/api-webhooks.md", bodyType: "form" },
  "app/routes/api+/stripe-webhook.tsx": { ownerArea: "billing", exposure: "providerOnly", docsGuide: "docs/api-webhooks.md", bodyType: "rawWebhook", authClass: "stripeSignature", notes: "Stripe-Signature header required; see docs/stripe-webhook.md." },
  "app/routes/api+/survey-answer.tsx": { ownerArea: "surveys", exposure: "publicUnauthenticated", docsGuide: "docs/api-internal-unsupported.md", bodyType: "form", authClass: "publicForm", specTarget: "publicOpenApi", notes: "Public survey respondent flow." },
  "app/routes/api+/survey-complete.tsx": { ownerArea: "surveys", exposure: "publicUnauthenticated", docsGuide: "docs/api-internal-unsupported.md", bodyType: "form", authClass: "publicForm", specTarget: "publicOpenApi" },
  "app/routes/api+/survey-responses.tsx": { ownerArea: "surveys", exposure: "sessionOnly", docsGuide: "docs/api-data-management.md", bodyType: "form", authClass: "session" },
  "app/routes/api+/surveys.tsx": { ownerArea: "surveys", exposure: "sessionOnly", docsGuide: "docs/api-data-management.md", bodyType: "json", authClass: "session" },
  "app/routes/api+/test-webhook.tsx": { ownerArea: "workspace", exposure: "sessionOnly", docsGuide: "docs/api-workspace-admin.md", bodyType: "json", authClass: "workspaceAdmin", workspaceScoped: true },
  "app/routes/api+/token.tsx": { ownerArea: "telephony", exposure: "sessionOnly", docsGuide: "docs/api-telephony-control.md", authClass: "session", workspaceScoped: true, notes: "Twilio client access token for browser dialer." },
  "app/routes/api+/verify-audio-pin/$pin.route.tsx": { ownerArea: "telephony", exposure: "publicUnauthenticated", docsGuide: "docs/api-internal-unsupported.md", authClass: "publicForm", specTarget: "publicOpenApi", notes: "Retired audio PIN flow; returns 410." },
  "app/routes/api+/verify-audio-session.tsx": { ownerArea: "telephony", exposure: "sessionOnly", docsGuide: "docs/api-telephony-control.md", bodyType: "form", authClass: "session", notes: "Retired audio PIN flow; both methods return 410." },
  "app/routes/api+/verify-call-in-session.tsx": { ownerArea: "telephony", exposure: "sessionOnly", docsGuide: "docs/api-telephony-control.md", authClass: "session" },
  "app/routes/api+/verify-pin-input.tsx": { ownerArea: "telephony", exposure: "internalOnly", docsGuide: "docs/api-internal-unsupported.md", bodyType: "form", authClass: "internalTrusted", notes: "Retired audio PIN flow; returns 410." },
  "app/routes/api+/workspace-api-keys.tsx": { ownerArea: "workspace", exposure: "sessionOnly", docsGuide: "docs/api-workspace-admin.md", bodyType: "json", authClass: "workspaceAdmin", workspaceScoped: true, notes: "Legacy flat route; workspace_id comes from the body/query. The admin floor and the capability-scope cap are enforced by requireApiKeyManager / assertScopesWithinActorRole in platform-members.server.ts (issue #1264)." },
  "app/routes/api+/twilio/trusthub/status.route.tsx": { ownerArea: "messaging", exposure: "providerOnly", docsGuide: "docs/api-webhooks.md", bodyType: "form", authClass: "twilioSignature", notes: "Trust Hub status_callback receiver; resolves workspace by customer-profile bundle SID and reconciles compliance status." },
  "app/routes/api+/twilio/a2p/events.route.tsx": { ownerArea: "messaging", exposure: "internalOnly", docsGuide: "docs/api-internal-unsupported.md", bodyType: "json", notes: "A2P Event Streams sink receiver (JSON body), gated by the TWILIO_EVENTS_SINK_SECRET shared secret (?token=… on the sink URL). Parses brand/campaign lifecycle events and reconciles workspace onboarding status." },
  "app/routes/api+/auth/register.route.tsx": { ownerArea: "auth", exposure: "publicUnauthenticated", docsGuide: "docs/api-agent-quickstart.md", bodyType: "json", specTarget: "publicOpenApi" },
  "app/routes/api+/auth/token.route.tsx": { ownerArea: "auth", exposure: "publicUnauthenticated", docsGuide: "docs/api-agent-quickstart.md", bodyType: "json", specTarget: "publicOpenApi" },
  "app/routes/api+/auth/refresh.route.tsx": { ownerArea: "auth", exposure: "publicUnauthenticated", docsGuide: "docs/api-agent-quickstart.md", bodyType: "json", specTarget: "publicOpenApi" },
  "app/routes/api+/auth/signout.route.tsx": { ownerArea: "auth", exposure: "sessionOnly", docsGuide: "docs/api-agent-quickstart.md", bodyType: "json", authClass: "session" },
  "app/routes/api+/auth/forgot-password.route.tsx": { ownerArea: "auth", exposure: "publicUnauthenticated", docsGuide: "docs/api-agent-quickstart.md", bodyType: "json", specTarget: "publicOpenApi" },
  "app/routes/api+/auth/reset-password.route.tsx": { ownerArea: "auth", exposure: "publicUnauthenticated", docsGuide: "docs/api-agent-quickstart.md", bodyType: "json", specTarget: "publicOpenApi" },
  "app/routes/api+/auth/verify-email.route.tsx": { ownerArea: "auth", exposure: "publicUnauthenticated", docsGuide: "docs/api-agent-quickstart.md", bodyType: "json", specTarget: "publicOpenApi" },
  "app/routes/api+/auth/invites.route.tsx": { ownerArea: "auth", exposure: "sessionOnly", docsGuide: "docs/api-agent-quickstart.md", bodyType: "json", authClass: "session" },
  "app/routes/api+/me.route.tsx": { ownerArea: "auth", exposure: "sessionOnly", docsGuide: "docs/api-agent-quickstart.md", bodyType: "json", authClass: "session" },
  "app/routes/api+/workspaces.route.tsx": { ownerArea: "workspace", exposure: "sessionOnly", docsGuide: "docs/api-agent-quickstart.md", bodyType: "json", authClass: "session" },
  "app/routes/api+/workspaces+/$workspaceId/route.tsx": { ownerArea: "workspace", exposure: "sessionOnly", docsGuide: "docs/api-agent-quickstart.md", bodyType: "json", workspaceScoped: true, notes: "Child index under data-plane layout middleware. GET supports session or API key with campaigns.read; PATCH requires admin+ session; DELETE requires owner session." },
  "app/routes/api+/workspaces+/$workspaceId/transfer-ownership.route.tsx": { ownerArea: "workspace", exposure: "sessionOnly", docsGuide: "docs/api-workspace-admin.md", bodyType: "json", authClass: "workspaceAdmin", workspaceScoped: true },
  "app/routes/api+/workspaces+/$workspaceId/billing.route.tsx": { ownerArea: "billing", exposure: "sessionOnly", docsGuide: "docs/api-agent-quickstart.md", authClass: "workspaceAdmin", workspaceScoped: true },
  "app/routes/api+/workspaces+/$workspaceId/credits.route.tsx": { ownerArea: "billing", exposure: "sessionOnly", docsGuide: "docs/api-agent-quickstart.md", workspaceScoped: true, notes: "Read current workspace credit balance. Available to any workspace member, including the caller role — the call screen polls it for live balance reconciliation." },
  "app/routes/api+/workspaces+/$workspaceId/billing/checkout-session.route.tsx": { ownerArea: "billing", exposure: "sessionOnly", docsGuide: "docs/api-agent-quickstart.md", bodyType: "json", authClass: "workspaceAdmin", workspaceScoped: true },
  "app/routes/api+/workspaces+/$workspaceId/billing/receipt.route.tsx": { ownerArea: "billing", exposure: "sessionOnly", docsGuide: "docs/api-agent-quickstart.md", bodyType: "query", workspaceScoped: true },
  "app/routes/api+/workspaces+/$workspaceId/billing/sessions/$sessionId.route.tsx": { ownerArea: "billing", exposure: "sessionOnly", docsGuide: "docs/api-agent-quickstart.md", authClass: "workspaceAdmin", workspaceScoped: true },
  "app/routes/api+/workspaces+/$workspaceId/onboarding.route.tsx": { ownerArea: "telephony", exposure: "sessionOnly", docsGuide: "docs/api-telephony-provisioning.md", bodyType: "json", authClass: "workspaceAdmin", workspaceScoped: true },
  "app/routes/api+/workspaces+/$workspaceId/onboarding/actions.route.tsx": { ownerArea: "telephony", exposure: "sessionOnly", docsGuide: "docs/api-telephony-provisioning.md", bodyType: "json", authClass: "workspaceAdmin", workspaceScoped: true },
  "app/routes/api+/workspaces+/$workspaceId/numbers.route.tsx": { ownerArea: "telephony", exposure: "sessionOnly", docsGuide: "docs/api-telephony-provisioning.md", bodyType: "json", workspaceScoped: true, notes: "GET lists numbers for any workspace member. POST (purchase) requires the member role or above; the caller role receives 403." },
  "app/routes/api+/workspaces+/$workspaceId/numbers/$numberId.route.tsx": { ownerArea: "telephony", exposure: "sessionOnly", docsGuide: "docs/api-telephony-provisioning.md", bodyType: "json", authClass: "workspaceAdmin", workspaceScoped: true },
  "app/routes/api+/workspaces+/$workspaceId/webhook.route.tsx": { ownerArea: "workspace", exposure: "sessionOnly", docsGuide: "docs/api-workspace-admin.md", bodyType: "json", authClass: "workspaceAdmin", workspaceScoped: true, notes: "POST tests webhook delivery." },
  "app/routes/api+/workspaces+/$workspaceId/members.route.tsx": { ownerArea: "workspace", exposure: "sessionOnly", docsGuide: "docs/api-workspace-admin.md", bodyType: "json", authClass: "workspaceAdmin", workspaceScoped: true, notes: "GET/PATCH/DELETE are session-only. POST invite accepts session or API key with members.invite." },
  "app/routes/api+/workspaces+/$workspaceId/api-keys.route.tsx": { ownerArea: "workspace", exposure: "sessionOnly", docsGuide: "docs/api-workspace-admin.md", bodyType: "json", authClass: "workspaceAdmin", workspaceScoped: true, notes: "Session-only: API-key actors get 401, so a key cannot mint another key. GET/POST/DELETE all require an admin session (requireApiKeyManager). POST caps requested scopes at the creator's own role capabilities and 403s naming any scope beyond them (issue #1264)." },
  "app/routes/api+/workspaces+/$workspaceId/audit-events.route.tsx": { ownerArea: "workspace", exposure: "sessionOnly", docsGuide: "docs/api-workspace-admin.md", workspaceScoped: true, notes: "Requires owner session (via role matrix) or an API key with audit.read." },
  "app/routes/api+/workspaces+/$workspaceId/campaigns.route.tsx": { ownerArea: "campaigns", exposure: "sessionOnly", docsGuide: "docs/api-data-plane.md", workspaceScoped: true },
  "app/routes/api+/campaigns/$campaignId.route.tsx": { ownerArea: "campaigns", exposure: "sessionOnly", docsGuide: "docs/api-data-plane.md", bodyType: "json" },
  "app/routes/api+/campaigns/$campaignId/queue.route.tsx": { ownerArea: "campaigns", exposure: "sessionOnly", docsGuide: "docs/api-data-plane.md", bodyType: "json" },
  "app/routes/api+/campaigns+/$campaignId/results.route.tsx": { ownerArea: "analytics", exposure: "sessionOnly", docsGuide: "docs/api-analytics-export.md", authClass: "session" },
  "app/routes/api+/campaigns+/$campaignId/call-session.route.tsx": { ownerArea: "telephony", exposure: "sessionOnly", docsGuide: "docs/api-live-operations.md", authClass: "session" },
  "app/routes/api+/campaigns+/$campaignId/call-session/release.route.tsx": { ownerArea: "telephony", exposure: "sessionOnly", docsGuide: "docs/api-live-operations.md", bodyType: "json", authClass: "session" },
  "app/routes/api+/workspaces+/$workspaceId/contacts.route.tsx": { ownerArea: "contacts", exposure: "sessionOnly", docsGuide: "docs/api-data-plane.md", workspaceScoped: true },
  "app/routes/api+/contacts/$contactId.route.tsx": { ownerArea: "contacts", exposure: "sessionOnly", docsGuide: "docs/api-data-plane.md", bodyType: "json" },
  "app/routes/api+/workspaces+/$workspaceId/audiences.route.tsx": { ownerArea: "audiences", exposure: "sessionOnly", docsGuide: "docs/api-data-plane.md", workspaceScoped: true },
  "app/routes/api+/workspaces+/$workspaceId/audiences/$audienceId.route.tsx": { ownerArea: "audiences", exposure: "sessionOnly", docsGuide: "docs/api-data-plane.md", workspaceScoped: true },
  "app/routes/api+/workspaces+/$workspaceId/audience-uploads/$uploadId.route.tsx": { ownerArea: "audiences", exposure: "sessionOnly", docsGuide: "docs/api-data-plane.md", workspaceScoped: true },
  "app/routes/api+/workspaces+/$workspaceId/scripts.route.tsx": { ownerArea: "scripts", exposure: "sessionOnly", docsGuide: "docs/api-data-plane.md", workspaceScoped: true },
  "app/routes/api+/scripts/$scriptId.route.tsx": { ownerArea: "scripts", exposure: "sessionOnly", docsGuide: "docs/api-data-plane.md" },
  "app/routes/api+/workspaces+/$workspaceId/surveys.route.tsx": { ownerArea: "surveys", exposure: "sessionOnly", docsGuide: "docs/api-data-plane.md", workspaceScoped: true },
  "app/routes/api+/surveys/$surveyId.route.tsx": { ownerArea: "surveys", exposure: "sessionOnly", docsGuide: "docs/api-data-plane.md" },
  "app/routes/api+/surveys/$surveyId/responses.route.tsx": { ownerArea: "surveys", exposure: "sessionOnly", docsGuide: "docs/api-data-plane.md" },
  "app/routes/api+/surveys+/$surveyId/responses/export.route.tsx": { ownerArea: "analytics", exposure: "sessionOnly", docsGuide: "docs/api-analytics-export.md", authClass: "session" },
  "app/routes/api+/workspaces+/$workspaceId/conversations.route.tsx": { ownerArea: "messaging", exposure: "sessionOnly", docsGuide: "docs/api-data-plane.md", workspaceScoped: true },
  "app/routes/api+/workspaces+/$workspaceId/conversations/$contactNumber.route.tsx": { ownerArea: "messaging", exposure: "sessionOnly", docsGuide: "docs/api-data-plane.md", authClass: "apiKeyOrSession", workspaceScoped: true },
  "app/routes/api+/workspaces+/$workspaceId/audios.route.tsx": { ownerArea: "media", exposure: "sessionOnly", docsGuide: "docs/api-analytics-export.md", bodyType: "multipart", workspaceScoped: true },
  "app/routes/api+/workspaces+/$workspaceId/voicemails.route.tsx": { ownerArea: "media", exposure: "sessionOnly", docsGuide: "docs/api-analytics-export.md", workspaceScoped: true },
  "app/routes/api+/workspaces+/$workspaceId/analytics.route.tsx": { ownerArea: "analytics", exposure: "sessionOnly", docsGuide: "docs/api-analytics-export.md", workspaceScoped: true },
  "app/routes/api+/workspaces+/$workspaceId/client-flash.route.tsx": { ownerArea: "misc", exposure: "sessionOnly", docsGuide: "docs/api-live-operations.md", bodyType: "json", workspaceScoped: true, notes: "Telemetry sink for client flash events (transient error toasts/banners, #1293): logs each event server-side; no reads, no state." },
  "app/routes/api+/workspaces+/$workspaceId/exports.route.tsx": { ownerArea: "analytics", exposure: "sessionOnly", docsGuide: "docs/api-analytics-export.md", bodyType: "json", workspaceScoped: true },
  "app/routes/api+/workspaces+/$workspaceId/calls.route.tsx": { ownerArea: "telephony", exposure: "sessionOnly", docsGuide: "docs/api-live-operations.md", workspaceScoped: true },
  "app/routes/api+/workspaces+/$workspaceId/calls/listening.route.tsx": { ownerArea: "telephony", exposure: "sessionOnly", docsGuide: "docs/api-live-operations.md", bodyType: "json", workspaceScoped: true },
  "app/routes/api+/workspaces+/$workspaceId/calls/$callSid/disconnect.route.tsx": { ownerArea: "telephony", exposure: "sessionOnly", docsGuide: "docs/api-telephony-provisioning.md", bodyType: "json", workspaceScoped: true, notes: "Workspace-scoped call disconnect using workspace Twilio credentials. Capability: calls.control." },
  "app/routes/api+/workspaces+/$workspaceId/campaigns/$campaignId/dialer/start.route.tsx": { ownerArea: "dialer", exposure: "sessionOnly", docsGuide: "docs/api-telephony-provisioning.md", bodyType: "json", workspaceScoped: true, notes: "Start predictive/manual auto-dial conference for authenticated caller+ agent. Capability: calls.start." },
  "app/routes/api+/workspaces+/$workspaceId/handset/session.route.tsx": { ownerArea: "telephony", exposure: "sessionOnly", docsGuide: "docs/api-live-operations.md", bodyType: "json", workspaceScoped: true },
  "app/routes/api+/admin+/dashboard.route.tsx": { ownerArea: "misc", exposure: "internalOnly", docsGuide: "docs/api-admin.md", bodyType: "json", specTarget: "publicOpenApi", notes: "Sudo-only admin dashboard and actions." },
  "app/routes/api+/admin+/users+/$userId.route.tsx": { ownerArea: "misc", exposure: "internalOnly", docsGuide: "docs/api-admin.md", bodyType: "json", specTarget: "publicOpenApi" },
  "app/routes/api+/admin+/users+/$userId/workspaces.route.tsx": { ownerArea: "misc", exposure: "internalOnly", docsGuide: "docs/api-admin.md", bodyType: "json", specTarget: "publicOpenApi" },
  "app/routes/api+/admin+/workspaces+/$workspaceId/twilio.route.tsx": { ownerArea: "misc", exposure: "internalOnly", docsGuide: "docs/api-admin.md", bodyType: "json", specTarget: "publicOpenApi" },
  "app/routes/api+/auth/$.route.tsx": { ownerArea: "auth", exposure: "publicUnauthenticated", docsGuide: "docs/api-auth-matrix.md", bodyType: "json", authClass: "publicForm", specTarget: "publicOpenApi", notes: "Better Auth catch-all (sign-in, session, sign-out, OAuth callbacks). POSTs are rate-limited: sign-in/two-factor 10/min per IP, other POSTs 30/min." },
  "app/routes/api+/acd-router.route.tsx": { ownerArea: "telephony", exposure: "internalOnly", docsGuide: "docs/api-live-operations.md", bodyType: "twiml", specTarget: "publicOpenApi", notes: "Twilio ACD wait URL." },
  "app/routes/api+/acd-router/agent-bridge.route.tsx": { ownerArea: "telephony", exposure: "internalOnly", docsGuide: "docs/api-live-operations.md", bodyType: "twiml", specTarget: "publicOpenApi" },
  "app/routes/api+/acd-router/agent-status.route.tsx": { ownerArea: "telephony", exposure: "internalOnly", docsGuide: "docs/api-live-operations.md", bodyType: "twiml", specTarget: "publicOpenApi" },
  "app/routes/api+/acd-router/complete.route.tsx": { ownerArea: "telephony", exposure: "internalOnly", docsGuide: "docs/api-live-operations.md", bodyType: "twiml", specTarget: "publicOpenApi" },
  "app/routes/api+/workspaces+/$workspaceId/audiences/$audienceId/uploads.route.tsx": { ownerArea: "audiences", exposure: "sessionOnly", docsGuide: "docs/api-data-plane.md", workspaceScoped: true },
  "app/routes/api+/workspaces+/$workspaceId/events.route.tsx": { ownerArea: "misc", exposure: "sessionOnly", docsGuide: "docs/api-live-operations.md", authClass: "session", workspaceScoped: true, notes: "SSE stream for workspace events (activity log)." },
};
