import type { ApiSurfaceEntry } from "@/lib/api-surface-types";
import { PLATFORM_GUIDE as GUIDE, platformSeed } from "@/lib/api-surface-seeds";
import { PLATFORM_API_SURFACE_2 } from "@/lib/api-surface-platform-2";

/**
 * Platform (agent-friendly CaaS) API surface entries. Part 1 of 2 — the rest
 * live in api-surface-platform-2.ts (positional split for the app file-size
 * gate, #1048); entry order feeds generated output and must be preserved.
 */
export const PLATFORM_API_SURFACE: readonly ApiSurfaceEntry[] = [
  platformSeed({
    path: "/api/auth/register",
    routeModule: "app/routes/api+/auth/register.route.tsx",
    authClass: "publicForm",
    ownerArea: "auth",
    exposure: "publicUnauthenticated",
    docsGuide: GUIDE.platform,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  platformSeed({
    path: "/api/auth/token",
    routeModule: "app/routes/api+/auth/token.route.tsx",
    authClass: "publicForm",
    ownerArea: "auth",
    exposure: "publicUnauthenticated",
    docsGuide: GUIDE.platform,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  platformSeed({
    path: "/api/auth/refresh",
    routeModule: "app/routes/api+/auth/refresh.route.tsx",
    authClass: "publicForm",
    ownerArea: "auth",
    exposure: "publicUnauthenticated",
    docsGuide: GUIDE.platform,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  platformSeed({
    path: "/api/auth/signout",
    routeModule: "app/routes/api+/auth/signout.route.tsx",
    authClass: "session",
    ownerArea: "auth",
    exposure: "sessionOnly",
    docsGuide: GUIDE.platform,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  platformSeed({
    path: "/api/auth/forgot-password",
    routeModule: "app/routes/api+/auth/forgot-password.route.tsx",
    authClass: "publicForm",
    ownerArea: "auth",
    exposure: "publicUnauthenticated",
    docsGuide: GUIDE.platform,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  platformSeed({
    path: "/api/auth/reset-password",
    routeModule: "app/routes/api+/auth/reset-password.route.tsx",
    authClass: "session",
    ownerArea: "auth",
    exposure: "sessionOnly",
    docsGuide: GUIDE.platform,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  platformSeed({
    path: "/api/auth/verify-email",
    routeModule: "app/routes/api+/auth/verify-email.route.tsx",
    authClass: "publicForm",
    ownerArea: "auth",
    exposure: "publicUnauthenticated",
    docsGuide: GUIDE.platform,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  platformSeed({
    path: "/api/auth/invites",
    routeModule: "app/routes/api+/auth/invites.route.tsx",
    authClass: "session",
    ownerArea: "auth",
    exposure: "sessionOnly",
    docsGuide: GUIDE.platform,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/me",
    routeModule: "app/routes/api+/me.route.tsx",
    authClass: "session",
    ownerArea: "auth",
    exposure: "sessionOnly",
    docsGuide: GUIDE.platform,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "PATCH", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/workspaces",
    routeModule: "app/routes/api+/workspaces.route.tsx",
    authClass: "session",
    ownerArea: "workspace",
    exposure: "sessionOnly",
    docsGuide: GUIDE.platform,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "workspace",
    exposure: "sessionOnly",
    docsGuide: GUIDE.platform,
    workspaceScoped: true,
    operations: [
      {
        method: "GET",
        handler: "loader",
        bodyType: "query",
        capability: "campaigns.read",
      },
      { method: "PATCH", handler: "action", bodyType: "json" },
      { method: "DELETE", handler: "action", bodyType: "json" },
    ],
    notes:
      "Child index under data-plane layout middleware. GET supports session or API key with campaigns.read; PATCH requires admin+ session; DELETE requires owner session.",
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId",
    routeModule: "app/routes/api+/workspaces+/$workspaceId.tsx",
    authClass: "session",
    ownerArea: "workspace",
    exposure: "sessionOnly",
    docsGuide: GUIDE.platform,
    workspaceScoped: true,
    duplicate: true,
    notes: "Middleware layout for nested workspace API routes; no direct handler.",
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/transfer-ownership",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/transfer-ownership.route.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "workspace",
    exposure: "sessionOnly",
    docsGuide: GUIDE.workspace,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/billing",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/billing.route.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "billing",
    exposure: "sessionOnly",
    docsGuide: GUIDE.platform,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/credits",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/credits.route.tsx",
    authClass: "session",
    ownerArea: "billing",
    exposure: "sessionOnly",
    docsGuide: GUIDE.platform,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
    notes:
      "Read current workspace credit balance. Available to any workspace " +
      "member, including the caller role — the call screen polls it for live " +
      "balance reconciliation.",
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/billing/checkout-session",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/billing/checkout-session.route.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "billing",
    exposure: "sessionOnly",
    docsGuide: GUIDE.platform,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/billing/sessions/:sessionId",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/billing/sessions/$sessionId.route.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "billing",
    exposure: "sessionOnly",
    docsGuide: GUIDE.platform,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/onboarding",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/onboarding.route.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "PATCH", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/onboarding/actions",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/onboarding/actions.route.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/numbers",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/numbers.route.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/numbers/:numberId",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/numbers/$numberId.route.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [
      { method: "PATCH", handler: "action", bodyType: "json" },
      { method: "DELETE", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/webhook",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/webhook.route.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "workspace",
    exposure: "sessionOnly",
    docsGuide: GUIDE.workspace,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "PUT", handler: "action", bodyType: "json" },
      { method: "POST", handler: "action", bodyType: "json" },
    ],
    notes: "POST tests webhook delivery.",
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/members",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/members.route.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "workspace",
    exposure: "sessionOnly",
    docsGuide: GUIDE.workspace,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      {
        method: "POST",
        handler: "action",
        bodyType: "json",
        capability: "members.invite",
      },
      { method: "PATCH", handler: "action", bodyType: "json" },
      { method: "DELETE", handler: "action", bodyType: "json" },
    ],
    notes:
      "GET/PATCH/DELETE are session-only. POST invite accepts session or API key with members.invite.",
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/api-keys",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/api-keys.route.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "workspace",
    exposure: "sessionOnly",
    docsGuide: GUIDE.workspace,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "json" },
      { method: "DELETE", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/audit-events",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/audit-events.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "workspace",
    exposure: "sessionOnly",
    docsGuide: GUIDE.workspace,
    workspaceScoped: true,
    operations: [
      {
        method: "GET",
        handler: "loader",
        bodyType: "query",
        capability: "audit.read",
      },
    ],
    notes:
      "Requires owner session (via role matrix) or an API key with audit.read.",
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/campaigns",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/campaigns.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "campaigns",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    workspaceScoped: true,
    operations: [
      {
        method: "GET",
        handler: "loader",
        bodyType: "query",
        capability: "campaigns.read",
      },
    ],
  }),
  platformSeed({
    path: "/api/campaigns/:campaignId",
    routeModule: "app/routes/api+/campaigns/$campaignId.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "campaigns",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [
      {
        method: "GET",
        handler: "loader",
        bodyType: "query",
        capability: "campaigns.read",
      },
      {
        method: "POST",
        handler: "action",
        bodyType: "json",
        capability: "campaigns.write",
      },
    ],
  }),
  platformSeed({
    path: "/api/campaigns/:campaignId/queue",
    routeModule: "app/routes/api+/campaigns/$campaignId/queue.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "campaigns",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [
      {
        method: "GET",
        handler: "loader",
        bodyType: "query",
        capability: "campaigns.read",
      },
      {
        method: "PATCH",
        handler: "action",
        bodyType: "json",
        capability: "campaigns.write",
      },
    ],
  }),
  platformSeed({
    path: "/api/campaigns/:campaignId/results",
    routeModule: "app/routes/api+/campaigns+/$campaignId/results.route.tsx",
    authClass: "session",
    ownerArea: "analytics",
    exposure: "sessionOnly",
    docsGuide: GUIDE.analytics,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/campaigns/:campaignId/call-session",
    routeModule: "app/routes/api+/campaigns+/$campaignId/call-session.route.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.live,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/campaigns/:campaignId/call-session/release",
    routeModule:
      "app/routes/api+/campaigns+/$campaignId/call-session/release.route.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.live,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/contacts",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/contacts.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "contacts",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    workspaceScoped: true,
    operations: [{
        method: "GET",
        handler: "loader",
        bodyType: "query",
        capability: "campaigns.read",
      }],
  }),
  ...PLATFORM_API_SURFACE_2,
];
