import {
  isUserFacingAuthClass,
} from "@/lib/public-api";
import type {
  ApiSurfaceEntry,
  AuthClass,
  BodyType,
  HttpMethod,
  OwnerArea,
} from "@/lib/api-surface-types";
import { PLATFORM_API_SURFACE } from "@/lib/api-surface-platform";
import {
  AUTH_CLASSES,
  BODY_TYPES,
  EXPOSURE_CLASSES,
  OWNER_AREAS,
  SPEC_TARGETS,
  surfaceEntryKey,
} from "@/lib/api-surface-types";

export type {
  ApiSurfaceEntry,
  ApiSurfaceOperation,
  AuthClass,
  BodyType,
  ExposureClass,
  HandlerType,
  HttpMethod,
  OwnerArea,
  SpecTarget,
} from "@/lib/api-surface-types";

export {
  AUTH_CLASSES,
  AUTH_CLASS_TAGS,
  BODY_TYPES,
  EXPOSURE_CLASSES,
  HTTP_METHODS,
  OWNER_AREAS,
  SPEC_TARGETS,
  surfaceEntryKey,
} from "@/lib/api-surface-types";

type Op = {
  method: HttpMethod;
  handler: "loader" | "action";
  bodyType: BodyType;
};

type Seed = {
  path: string;
  routeModule: string;
  authClass: AuthClass;
  ownerArea: OwnerArea;
  exposure: ApiSurfaceEntry["exposure"];
  supported?: boolean;
  specTarget?: ApiSurfaceEntry["specTarget"];
  docsGuide: string;
  operations: Op[];
  notes?: string;
  securityWarning?: string;
  duplicate?: boolean;
  duplicateGroup?: string;
  workspaceScoped?: boolean;
};

function isCompleteOnlySurface(input: Seed): boolean {
  if (input.duplicate) return true;
  if (input.exposure === "unsupported") return true;
  if (
    input.authClass === "weakUnknown" ||
    input.authClass === "internalTrusted" ||
    input.authClass === "twilioSignature" ||
    input.authClass === "stripeSignature"
  ) {
    return true;
  }
  return !isUserFacingAuthClass(input.authClass);
}

function seed(input: Seed): ApiSurfaceEntry {
  const specTarget =
    input.specTarget ??
    (isCompleteOnlySurface(input) ? "completeOpenApi" : "publicOpenApi");

  const supported =
    input.supported ??
    (specTarget === "publicOpenApi" && input.authClass !== "weakUnknown");

  return {
    path: input.path,
    routeModule: input.routeModule,
    operations: input.operations,
    authClass: input.authClass,
    ownerArea: input.ownerArea,
    exposure: input.exposure,
    supported,
    specTarget,
    docsGuide: input.docsGuide,
    notes: input.notes,
    securityWarning: input.securityWarning,
    duplicate: input.duplicate,
    duplicateGroup: input.duplicateGroup,
    workspaceScoped: input.workspaceScoped,
  };
}

const GUIDE = {
  auth: "docs/api-auth-matrix.md",
  workspace: "docs/api-workspace-admin.md",
  data: "docs/api-data-management.md",
  analytics: "docs/api-analytics-export.md",
  telephony: "docs/api-telephony-control.md",
  webhooks: "docs/api-webhooks.md",
  internal: "docs/api-internal-unsupported.md",
  overview: "docs/api-overview.md",
} as const;

/** Canonical inventory of callable HTTP API surfaces. */
export const API_SURFACE: readonly ApiSurfaceEntry[] = [
  seed({
    path: "/api/agent-status",
    routeModule: "app/routes/api+/agent-status.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "workspace",
    exposure: "sessionOnly",
    docsGuide: GUIDE.workspace,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "json" },
    ],
    notes: "Agent presence for workspace dialer sessions.",
  }),
  seed({
    path: "/api/audience-upload-status",
    routeModule: "app/routes/api+/audience-upload-status.tsx",
    authClass: "session",
    ownerArea: "audiences",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
    notes: "Poll audience CSV upload job status.",
  }),
  seed({
    path: "/api/audience-upload",
    routeModule: "app/routes/api+/audience-upload.tsx",
    authClass: "session",
    ownerArea: "audiences",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [{ method: "POST", handler: "action", bodyType: "multipart" }],
    notes: "Upload audience CSV with column mapping.",
  }),
  seed({
    path: "/api/audiences",
    routeModule: "app/routes/api+/audiences.tsx",
    authClass: "session",
    ownerArea: "audiences",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "PATCH", handler: "action", bodyType: "form" },
      { method: "DELETE", handler: "action", bodyType: "form" },
    ],
  }),
  seed({
    path: "/api/audiodrop",
    routeModule: "app/routes/api+/audiodrop.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
    notes: "Voicemail drop during live call.",
  }),
  seed({
    path: "/api/auth/callback",
    routeModule: "app/routes/api+/auth/callback.route.tsx",
    authClass: "publicForm",
    ownerArea: "auth",
    exposure: "publicUnauthenticated",
    docsGuide: GUIDE.auth,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
    notes: "Supabase auth callback; sets session cookies and redirects.",
  }),
  seed({
    path: "/api/auto-dial",
    routeModule: "app/routes/api+/auto-dial.tsx",
    authClass: "session",
    ownerArea: "dialer",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
    notes: "Start auto-dial session for workspace.",
  }),
  seed({
    path: "/api/auto-dial/:roomId",
    routeModule: "app/routes/api+/auto-dial/$roomId.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "dialer",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
    notes: "Twilio conference/AMD TwiML callback.",
  }),
  seed({
    path: "/api/auto-dial/dialer",
    routeModule: "app/routes/api+/auto-dial/dialer.route.tsx",
    authClass: "internalTrusted",
    ownerArea: "dialer",
    exposure: "internalOnly",
    docsGuide: GUIDE.internal,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
    securityWarning:
      "No user/API-key auth; trusts workspace_id/user_id in JSON body via service role.",
    notes: "Predictive/auto-dial worker endpoint.",
  }),
  seed({
    path: "/api/auto-dial/end",
    routeModule: "app/routes/api+/auto-dial/end.route.tsx",
    authClass: "session",
    ownerArea: "dialer",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  seed({
    path: "/api/auto-dial/status",
    routeModule: "app/routes/api+/auto-dial/status.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "dialer",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/call-status-poll",
    routeModule: "app/routes/api+/call-status-poll.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.analytics,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
    notes: "Poll Twilio call status for call-screen UI.",
  }),
  seed({
    path: "/api/call-status",
    routeModule: "app/routes/api+/call-status.tsx",
    authClass: "twilioSignature",
    ownerArea: "telephony",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/call",
    routeModule: "app/routes/api+/call.tsx",
    authClass: "internalTrusted",
    ownerArea: "handset",
    exposure: "internalOnly",
    docsGuide: GUIDE.internal,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
    securityWarning:
      "Twilio Voice URL without signature validation; handset path uses session cookie lookup.",
    notes: "Returns TwiML.",
  }),
  seed({
    path: "/api/caller-id",
    routeModule: "app/routes/api+/caller-id.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
    notes: "Start outbound caller-ID verification.",
  }),
  seed({
    path: "/api/caller-id/status",
    routeModule: "app/routes/api+/caller-id/status.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "telephony",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/campaign-export-status",
    routeModule: "app/routes/api+/campaign-export-status.tsx",
    authClass: "session",
    ownerArea: "analytics",
    exposure: "sessionOnly",
    docsGuide: GUIDE.analytics,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  seed({
    path: "/api/campaign-export",
    routeModule: "app/routes/api+/campaign-export.tsx",
    authClass: "session",
    ownerArea: "analytics",
    exposure: "sessionOnly",
    docsGuide: GUIDE.analytics,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/campaign_audience",
    routeModule: "app/routes/api+/campaign_audience.tsx",
    authClass: "session",
    ownerArea: "campaigns",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [
      { method: "POST", handler: "action", bodyType: "json" },
      { method: "DELETE", handler: "action", bodyType: "json" },
    ],
  }),
  seed({
    path: "/api/campaign_queue",
    routeModule: "app/routes/api+/campaign_queue.tsx",
    authClass: "session",
    ownerArea: "queues",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    operations: [
      { method: "POST", handler: "action", bodyType: "form" },
      { method: "DELETE", handler: "action", bodyType: "form" },
    ],
  }),
  seed({
    path: "/api/campaigns",
    routeModule: "app/routes/api+/campaigns.tsx",
    authClass: "session",
    ownerArea: "campaigns",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [
      { method: "POST", handler: "action", bodyType: "form" },
      { method: "PATCH", handler: "action", bodyType: "form" },
      { method: "DELETE", handler: "action", bodyType: "form" },
    ],
  }),
  seed({
    path: "/api/campaigns/create-with-script",
    routeModule: "app/routes/api+/campaigns/create-with-script.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "campaigns",
    exposure: "publicSdk",
    docsGuide: "docs/api-create-campaign-with-script.md",
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  seed({
    path: "/api/chat_sms",
    routeModule: "app/routes/api+/chat_sms.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "messaging",
    exposure: "publicSdk",
    docsGuide: "docs/api-send-sms.md",
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  seed({
    path: "/api/connect-campaign-conference/:workspaceId/:campaignId",
    routeModule:
      "app/routes/api+/connect-campaign-conference/$workspaceId/$campaignId.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "dialer",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
    notes: "Twilio voice URL after connect-phone-device; returns TwiML.",
  }),
  seed({
    path: "/api/connect-phone-device",
    routeModule: "app/routes/api+/connect-phone-device.tsx",
    authClass: "session",
    ownerArea: "dialer",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  seed({
    path: "/api/contact-audience",
    routeModule: "app/routes/api+/contact-audience.tsx",
    authClass: "session",
    ownerArea: "contacts",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [{ method: "DELETE", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/contact-audience/bulk-delete",
    routeModule: "app/routes/api+/contact-audience/bulk-delete.route.tsx",
    authClass: "session",
    ownerArea: "contacts",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [{ method: "DELETE", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/contact-form",
    routeModule: "app/routes/api+/contact-form.tsx",
    authClass: "publicForm",
    ownerArea: "misc",
    exposure: "publicUnauthenticated",
    docsGuide: GUIDE.internal,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
    notes: "Marketing contact form; sends email via Resend.",
  }),
  seed({
    path: "/api/contacts",
    routeModule: "app/routes/api+/contacts.tsx",
    authClass: "session",
    ownerArea: "contacts",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "form" },
      { method: "PATCH", handler: "action", bodyType: "form" },
    ],
  }),
  seed({
    path: "/api/dial",
    routeModule: "app/routes/api+/dial.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
    notes: "Campaign dial initiation; returns TwiML.",
  }),
  seed({
    path: "/api/dial/:number",
    routeModule: "app/routes/api+/dial/$number.route.tsx",
    authClass: "weakUnknown",
    ownerArea: "telephony",
    exposure: "internalOnly",
    docsGuide: GUIDE.internal,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
    securityWarning: "Twilio TwiML sub-route without signature validation.",
    notes: "Returns TwiML.",
  }),
  seed({
    path: "/api/dial/status",
    routeModule: "app/routes/api+/dial/status.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "telephony",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/docs/openapi",
    routeModule: "app/routes/api+/docs/openapi.route.tsx",
    authClass: "publicForm",
    ownerArea: "docs",
    exposure: "publicUnauthenticated",
    supported: true,
    specTarget: "inventoryOnly",
    docsGuide: GUIDE.overview,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
    notes: "Public user-facing OpenAPI JSON (session + workspace + integrator routes).",
  }),
  seed({
    path: "/api/docs/openapi/all",
    routeModule: "app/routes/api+/docs/openapi/all.route.tsx",
    authClass: "publicForm",
    ownerArea: "docs",
    exposure: "publicUnauthenticated",
    specTarget: "inventoryOnly",
    docsGuide: GUIDE.overview,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
    notes: "Complete classified API surface OpenAPI JSON.",
  }),
  seed({
    path: "/api/disconnect",
    routeModule: "app/routes/api.disconnect.ts",
    authClass: "weakUnknown",
    ownerArea: "telephony",
    exposure: "internalOnly",
    docsGuide: GUIDE.internal,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
    securityWarning:
      "Twilio Device disconnect using account credentials; no session or signature check.",
  }),
  seed({
    path: "/api/email-vm",
    routeModule: "app/routes/api+/email-vm.tsx",
    authClass: "twilioSignature",
    ownerArea: "telephony",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/error-report",
    routeModule: "app/routes/api+/error-report.tsx",
    authClass: "session",
    ownerArea: "misc",
    exposure: "sessionOnly",
    docsGuide: GUIDE.internal,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  seed({
    path: "/api/handset-token",
    routeModule: "app/routes/api+/handset-token.tsx",
    authClass: "session",
    ownerArea: "handset",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  seed({
    path: "/api/hangup",
    routeModule: "app/routes/api+/hangup.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/inbound-handset-dial-end",
    routeModule: "app/routes/api+/inbound-handset-dial-end.tsx",
    authClass: "twilioSignature",
    ownerArea: "handset",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/inbound-handset",
    routeModule: "app/routes/api+/inbound-handset.tsx",
    authClass: "twilioSignature",
    ownerArea: "handset",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/inbound-ivr/:numberId/:pageId",
    routeModule: "app/routes/api+/inbound-ivr/$numberId/$pageId.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "ivr",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
    notes: "Returns TwiML.",
  }),
  seed({
    path: "/api/inbound-ivr/:numberId/:pageId/:blockId",
    routeModule:
      "app/routes/api+/inbound-ivr/$numberId/$pageId/$blockId.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "ivr",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/inbound-ivr/:numberId/:pageId/:blockId/response",
    routeModule:
      "app/routes/api+/inbound-ivr/$numberId/$pageId/$blockId/response.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "ivr",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/inbound-queue",
    routeModule: "app/routes/api+/inbound-queue.tsx",
    authClass: "session",
    ownerArea: "inbound",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "json" },
      { method: "PUT", handler: "action", bodyType: "json" },
      { method: "PATCH", handler: "action", bodyType: "json" },
      { method: "DELETE", handler: "action", bodyType: "json" },
    ],
  }),
  seed({
    path: "/api/inbound-sms",
    routeModule: "app/routes/api+/inbound-sms.tsx",
    authClass: "twilioSignature",
    ownerArea: "messaging",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/inbound-verification",
    routeModule: "app/routes/api+/inbound-verification.tsx",
    authClass: "internalTrusted",
    ownerArea: "inbound",
    exposure: "internalOnly",
    docsGuide: GUIDE.internal,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
    securityWarning: "Call-in verification TwiML; service role, no Twilio signature.",
    notes: "Returns TwiML.",
  }),
  seed({
    path: "/api/inbound",
    routeModule: "app/routes/api+/inbound.tsx",
    authClass: "twilioSignature",
    ownerArea: "inbound",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
    notes: "Returns TwiML.",
  }),
  seed({
    path: "/api/initiate-ivr",
    routeModule: "app/routes/api+/initiate-ivr.tsx",
    authClass: "session",
    ownerArea: "ivr",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  seed({
    path: "/api/ivr",
    routeModule: "app/routes/api+/ivr.tsx",
    authClass: "session",
    ownerArea: "ivr",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/ivr/status",
    routeModule: "app/routes/api+/ivr/status.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "ivr",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/ivr/:campaignId/:pageId",
    routeModule: "app/routes/api+/ivr/$campaignId/$pageId.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "ivr",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
    notes: "Returns TwiML.",
  }),
  seed({
    path: "/api/ivr/:campaignId/:pageId/:blockId",
    routeModule: "app/routes/api+/ivr/$campaignId/$pageId/$blockId.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "ivr",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/ivr/:campaignId/:pageId/:blockId/response",
    routeModule:
      "app/routes/api+/ivr/$campaignId/$pageId/$blockId/response.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "ivr",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/media",
    routeModule: "app/routes/api+/media.tsx",
    authClass: "session",
    ownerArea: "media",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [{ method: "POST", handler: "action", bodyType: "multipart" }],
  }),
  seed({
    path: "/api/message_media",
    routeModule: "app/routes/api+/message_media.tsx",
    authClass: "session",
    ownerArea: "messaging",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [
      { method: "POST", handler: "action", bodyType: "multipart" },
      { method: "DELETE", handler: "action", bodyType: "form" },
    ],
  }),
  seed({
    path: "/api/numbers",
    routeModule: "app/routes/api+/numbers.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.workspace,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "form" },
    ],
  }),
  seed({
    path: "/api/outreach-attempts",
    routeModule: "app/routes/api+/outreach-attempts.tsx",
    authClass: "session",
    ownerArea: "campaigns",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
    notes: "Hyphenated path; preferred outreach attempt API.",
  }),
  seed({
    path: "/api/outreach_attempts/:id",
    routeModule: "app/routes/api+/outreach_attempts/$id.route.tsx",
    authClass: "weakUnknown",
    ownerArea: "campaigns",
    exposure: "unsupported",
    docsGuide: GUIDE.internal,
    duplicate: true,
    duplicateGroup: "outreach_attempts-id",
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
    securityWarning:
      "Session cookie client only; no verifyAuth. Duplicate legacy route also registered.",
    notes: "Updates outreach_attempt table.",
  }),
  seed({
    path: "/api/outreach_attempts/:id",
    routeModule: "app/routes/api.outreach_attempts.$id.js",
    authClass: "weakUnknown",
    ownerArea: "campaigns",
    exposure: "unsupported",
    docsGuide: GUIDE.internal,
    duplicate: true,
    duplicateGroup: "outreach_attempts-id",
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
    securityWarning:
      "Legacy JS module; updates outreach_attempts table (typo). Do not use for integrations.",
    notes: "Legacy flat-route duplicate of TS handler.",
  }),
  seed({
    path: "/api/questions",
    routeModule: "app/routes/api+/questions.tsx",
    authClass: "session",
    ownerArea: "campaigns",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
    notes: "Call disposition / survey question updates on call screen.",
  }),
  seed({
    path: "/api/queues",
    routeModule: "app/routes/api+/queues.tsx",
    authClass: "weakUnknown",
    ownerArea: "queues",
    exposure: "sessionOnly",
    docsGuide: GUIDE.internal,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "json" },
      { method: "DELETE", handler: "action", bodyType: "json" },
    ],
    securityWarning:
      "Uses session client but does not require authenticated user on all code paths.",
  }),
  seed({
    path: "/api/recording",
    routeModule: "app/routes/api+/recording.tsx",
    authClass: "twilioSignature",
    ownerArea: "telephony",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/reset_campaign",
    routeModule: "app/routes/api+/reset_campaign.tsx",
    authClass: "session",
    ownerArea: "campaigns",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/scripts",
    routeModule: "app/routes/api+/scripts.tsx",
    authClass: "session",
    ownerArea: "scripts",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  seed({
    path: "/api/sms",
    routeModule: "app/routes/api+/sms.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "messaging",
    exposure: "publicSdk",
    docsGuide: "docs/api-send-sms.md",
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  seed({
    path: "/api/sms/status",
    routeModule: "app/routes/api+/sms/status.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "messaging",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/stripe-webhook",
    routeModule: "app/routes/api+/stripe-webhook.tsx",
    authClass: "stripeSignature",
    ownerArea: "billing",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "rawWebhook" }],
    notes: "Stripe-Signature header required; see docs/stripe-webhook.md.",
  }),
  seed({
    path: "/api/survey-answer",
    routeModule: "app/routes/api+/survey-answer.tsx",
    authClass: "publicForm",
    ownerArea: "surveys",
    exposure: "publicUnauthenticated",
    docsGuide: GUIDE.internal,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
    notes: "Public survey respondent flow.",
  }),
  seed({
    path: "/api/survey-complete",
    routeModule: "app/routes/api+/survey-complete.tsx",
    authClass: "publicForm",
    ownerArea: "surveys",
    exposure: "publicUnauthenticated",
    docsGuide: GUIDE.internal,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/survey-responses",
    routeModule: "app/routes/api+/survey-responses.tsx",
    authClass: "session",
    ownerArea: "surveys",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/surveys",
    routeModule: "app/routes/api+/surveys.tsx",
    authClass: "session",
    ownerArea: "surveys",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [
      { method: "POST", handler: "action", bodyType: "json" },
      { method: "PATCH", handler: "action", bodyType: "json" },
      { method: "DELETE", handler: "action", bodyType: "json" },
    ],
  }),
  seed({
    path: "/api/test-webhook",
    routeModule: "app/routes/api+/test-webhook.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "workspace",
    exposure: "sessionOnly",
    docsGuide: GUIDE.workspace,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  seed({
    path: "/api/token",
    routeModule: "app/routes/api+/token.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
    notes: "Twilio client access token for browser dialer.",
  }),
  seed({
    path: "/api/verify-audio-pin/:pin",
    routeModule: "app/routes/api+/verify-audio-pin/$pin.route.tsx",
    authClass: "publicForm",
    ownerArea: "telephony",
    exposure: "publicUnauthenticated",
    docsGuide: GUIDE.internal,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
    notes: "Static TwiML gather entry; returns TwiML.",
  }),
  seed({
    path: "/api/verify-audio-session",
    routeModule: "app/routes/api+/verify-audio-session.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "form" },
    ],
    securityWarning:
      "GET requires session; POST action returns TwiML without auth check.",
  }),
  seed({
    path: "/api/verify-call-in-session",
    routeModule: "app/routes/api+/verify-call-in-session.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  seed({
    path: "/api/verify-pin-input",
    routeModule: "app/routes/api+/verify-pin-input.tsx",
    authClass: "internalTrusted",
    ownerArea: "telephony",
    exposure: "internalOnly",
    docsGuide: GUIDE.internal,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
    securityWarning: "Twilio gather callback; service role, no Twilio signature.",
    notes: "Returns TwiML.",
  }),
  seed({
    path: "/api/workspace-api-keys",
    routeModule: "app/routes/api+/workspace-api-keys.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "workspace",
    exposure: "sessionOnly",
    docsGuide: GUIDE.workspace,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "json" },
      { method: "DELETE", handler: "action", bodyType: "json" },
    ],
  }),
  seed({
    path: "/api/workspace",
    routeModule: "app/routes/api+/workspace.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "workspace",
    exposure: "sessionOnly",
    docsGuide: GUIDE.workspace,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  ...PLATFORM_API_SURFACE,
];

/** Flat map keyed by `METHOD /path` (includes duplicate legacy modules). */
export const API_SURFACE_BY_KEY = new Map(
  API_SURFACE.flatMap((entry) =>
    entry.operations.map((op) => [
      surfaceEntryKey(entry.path, op.method),
      { entry, operation: op },
    ]),
  ),
);

export function getPublicOpenApiEntries(): ApiSurfaceEntry[] {
  return API_SURFACE.filter((e) => e.specTarget === "publicOpenApi");
}

export function getCompleteOpenApiEntries(): ApiSurfaceEntry[] {
  return API_SURFACE.filter((e) => e.specTarget !== "inventoryOnly");
}

export function getPublicOpenApiPathsFromInventory(): string[] {
  return API_SURFACE.filter((e) => e.specTarget === "publicOpenApi").map(
    (e) => e.path,
  );
}

export const API_SURFACE_GUIDES = [
  "docs/api-auth-matrix.md",
  "docs/api-surface-inventory.md",
  "docs/api-workspace-admin.md",
  "docs/api-data-management.md",
  "docs/api-data-plane.md",
  "docs/api-analytics-export.md",
  "docs/api-telephony-control.md",
  "docs/api-telephony-provisioning.md",
  "docs/api-live-operations.md",
  "docs/api-webhooks.md",
  "docs/api-internal-unsupported.md",
  "docs/api-overview.md",
  "docs/api-agent-quickstart.md",
  "docs/api-admin.md",
  "docs/api-create-campaign-with-script.md",
  "docs/api-send-sms.md",
] as const;
