/**
 * Internal/session API surface entries — part 1 of 2.
 * Positional split for the app file-size gate (#1048): entry ORDER feeds the
 * generated inventory/OpenAPI output and must be preserved across the parts.
 */
import type { ApiSurfaceEntry } from "@/lib/api-surface-types";
import { GUIDE, seed } from "@/lib/api-surface-seeds";

export const INTERNAL_API_SURFACE_1: readonly ApiSurfaceEntry[] = [
  seed({
    path: "/api/agent-status",
    routeModule: "app/routes/api+/agent-status.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "workspace",
    exposure: "sessionOnly",
    docsGuide: GUIDE.workspace,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "json" },
    ],
    notes: "Agent presence for workspace dialer sessions.",
  }),
  seed({
    path: "/api/audience-upload-status",
    routeModule: "app/routes/api+/audience-upload-status.tsx",
    authClass: "session",
    ownerArea: "audiences",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
    notes: "Poll audience CSV upload job status.",
  }),
  seed({
    path: "/api/audience-upload",
    routeModule: "app/routes/api+/audience-upload.tsx",
    authClass: "session",
    ownerArea: "audiences",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [{ method: "POST", handler: "action", bodyType: "multipart" }],
    notes: "Upload audience CSV with column mapping.",
  }),
  seed({
    path: "/api/audiences",
    routeModule: "app/routes/api+/audiences.tsx",
    authClass: "session",
    ownerArea: "audiences",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    workspaceScoped: true,
    operations: [
      {
        method: "GET",
        handler: "loader",
        bodyType: "query",
        capability: "campaigns.read",
      },
      {
        method: "PATCH",
        handler: "action",
        bodyType: "form",
        capability: "campaigns.write",
      },
      {
        method: "DELETE",
        handler: "action",
        bodyType: "form",
        capability: "campaigns.write",
      },
    ],
  }),
  seed({
    path: "/api/audiodrop",
    routeModule: "app/routes/api+/audiodrop.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
    notes: "Voicemail drop during live call.",
  }),
  seed({
    path: "/api/auth/callback",
    routeModule: "app/routes/api+/auth/callback.route.tsx",
    authClass: "publicForm",
    ownerArea: "auth",
    exposure: "publicUnauthenticated",
    docsGuide: GUIDE.auth,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
    notes: "Postgres auth callback; sets session cookies and redirects.",
  }),
  seed({
    path: "/api/auto-dial/:roomId",
    routeModule: "app/routes/api+/auto-dial/$roomId.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "dialer",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
    notes: "Twilio conference/AMD TwiML callback.",
  }),
  seed({
    path: "/api/auto-dial/end",
    routeModule: "app/routes/api+/auto-dial/end.route.tsx",
    authClass: "session",
    ownerArea: "dialer",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  seed({
    path: "/api/auto-dial/status",
    routeModule: "app/routes/api+/auto-dial/status.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "dialer",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/call-status-poll",
    routeModule: "app/routes/api+/call-status-poll.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.analytics,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
    notes: "Poll Twilio call status for call-screen UI.",
  }),
  seed({
    path: "/api/call-status",
    routeModule: "app/routes/api+/call-status.tsx",
    authClass: "twilioSignature",
    ownerArea: "telephony",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/call",
    routeModule: "app/routes/api+/call.tsx",
    authClass: "internalTrusted",
    ownerArea: "handset",
    exposure: "internalOnly",
    docsGuide: GUIDE.internal,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
    securityWarning:
      "Twilio Voice URL without signature validation; handset path uses session cookie lookup.",
    notes: "Returns TwiML.",
  }),
  seed({
    path: "/api/caller-id",
    routeModule: "app/routes/api+/caller-id.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
    notes: "Start outbound caller-ID verification.",
  }),
  seed({
    path: "/api/caller-id/status",
    routeModule: "app/routes/api+/caller-id/status.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "telephony",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/campaign-export-status",
    routeModule: "app/routes/api+/campaign-export-status.tsx",
    authClass: "session",
    ownerArea: "analytics",
    exposure: "sessionOnly",
    docsGuide: GUIDE.analytics,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  seed({
    path: "/api/campaign-export",
    routeModule: "app/routes/api+/campaign-export.tsx",
    authClass: "session",
    ownerArea: "analytics",
    exposure: "sessionOnly",
    docsGuide: GUIDE.analytics,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/campaign_audience",
    routeModule: "app/routes/api+/campaign_audience.tsx",
    authClass: "session",
    ownerArea: "campaigns",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [
      { method: "POST", handler: "action", bodyType: "json" },
      { method: "DELETE", handler: "action", bodyType: "json" },
    ],
  }),
  seed({
    path: "/api/campaign_queue",
    routeModule: "app/routes/api+/campaign_queue.tsx",
    authClass: "session",
    ownerArea: "queues",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    operations: [
      { method: "POST", handler: "action", bodyType: "form" },
      { method: "DELETE", handler: "action", bodyType: "form" },
    ],
  }),
  seed({
    path: "/api/campaigns",
    routeModule: "app/routes/api+/campaigns.tsx",
    authClass: "session",
    ownerArea: "campaigns",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [
      { method: "POST", handler: "action", bodyType: "form" },
      { method: "PATCH", handler: "action", bodyType: "form" },
      { method: "DELETE", handler: "action", bodyType: "form" },
    ],
  }),
  seed({
    path: "/api/coaching-ack",
    routeModule: "app/routes/api+/coaching-ack.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  seed({
    path: "/api/campaigns/create-with-script",
    routeModule: "app/routes/api+/campaigns/create-with-script.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "campaigns",
    exposure: "publicSdk",
    docsGuide: "docs/api-create-campaign-with-script.md",
    workspaceScoped: true,
    operations: [
      {
        method: "POST",
        handler: "action",
        bodyType: "json",
        capability: "campaigns.write",
      },
    ],
  }),
  seed({
    path: "/api/chat_sms",
    routeModule: "app/routes/api+/chat_sms.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "messaging",
    exposure: "publicSdk",
    docsGuide: "docs/api-send-sms.md",
    workspaceScoped: true,
    operations: [
      {
        method: "POST",
        handler: "action",
        bodyType: "json",
        capability: "messages.send",
      },
    ],
  }),
  seed({
    path: "/api/connect-campaign-conference/:workspaceId/:campaignId",
    routeModule:
      "app/routes/api+/connect-campaign-conference/$workspaceId/$campaignId.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "dialer",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
    notes: "Twilio voice URL after connect-phone-device; returns TwiML.",
  }),
  seed({
    path: "/api/connect-phone-device",
    routeModule: "app/routes/api+/connect-phone-device.tsx",
    authClass: "session",
    ownerArea: "dialer",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  seed({
    path: "/api/contact-audience",
    routeModule: "app/routes/api+/contact-audience.tsx",
    authClass: "session",
    ownerArea: "contacts",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [{ method: "DELETE", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/contact-audience/bulk-delete",
    routeModule: "app/routes/api+/contact-audience/bulk-delete.route.tsx",
    authClass: "session",
    ownerArea: "contacts",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [{ method: "DELETE", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/contact-form",
    routeModule: "app/routes/api+/contact-form.tsx",
    authClass: "publicForm",
    ownerArea: "misc",
    exposure: "publicUnauthenticated",
    docsGuide: GUIDE.internal,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
    notes: "Marketing contact form; sends email via Resend.",
  }),
  seed({
    path: "/api/contacts",
    routeModule: "app/routes/api+/contacts.tsx",
    authClass: "session",
    ownerArea: "contacts",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "form" },
      { method: "PATCH", handler: "action", bodyType: "form" },
    ],
  }),
  seed({
    path: "/api/dial",
    routeModule: "app/routes/api+/dial.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
    notes: "Campaign dial initiation; returns TwiML.",
  }),
  seed({
    path: "/api/dial/:number",
    routeModule: "app/routes/api+/dial/$number.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "telephony",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
    notes: "Twilio TwiML sub-route; requires a valid Twilio signature. Returns TwiML.",
  }),
  seed({
    path: "/api/dial/status",
    routeModule: "app/routes/api+/dial/status.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "telephony",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/docs/openapi",
    routeModule: "app/routes/api+/docs/openapi.route.tsx",
    authClass: "publicForm",
    ownerArea: "docs",
    exposure: "publicUnauthenticated",
    supported: true,
    specTarget: "inventoryOnly",
    docsGuide: GUIDE.overview,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
    notes: "Public user-facing OpenAPI JSON (session + workspace + integrator routes).",
  }),
  seed({
    path: "/api/docs/openapi/all",
    routeModule: "app/routes/api+/docs/openapi/all.route.tsx",
    authClass: "publicForm",
    ownerArea: "docs",
    exposure: "publicUnauthenticated",
    specTarget: "inventoryOnly",
    docsGuide: GUIDE.overview,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
    notes: "Complete classified API surface OpenAPI JSON.",
  }),
  seed({
    path: "/api/email-vm",
    routeModule: "app/routes/api+/email-vm.tsx",
    authClass: "twilioSignature",
    ownerArea: "telephony",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/error-report",
    routeModule: "app/routes/api+/error-report.tsx",
    authClass: "session",
    ownerArea: "misc",
    exposure: "sessionOnly",
    docsGuide: GUIDE.internal,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  seed({
    path: "/api/handset-token",
    routeModule: "app/routes/api+/handset-token.tsx",
    authClass: "session",
    ownerArea: "handset",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  seed({
    path: "/api/hangup",
    routeModule: "app/routes/api+/hangup.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/inbound-handset-dial-end",
    routeModule: "app/routes/api+/inbound-handset-dial-end.tsx",
    authClass: "twilioSignature",
    ownerArea: "handset",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/inbound-handset",
    routeModule: "app/routes/api+/inbound-handset.tsx",
    authClass: "twilioSignature",
    ownerArea: "handset",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/inbound-ivr/:numberId/:pageId",
    routeModule: "app/routes/api+/inbound-ivr/$numberId/$pageId.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "ivr",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
    notes: "Returns TwiML.",
  }),
  seed({
    path: "/api/inbound-ivr/:numberId/:pageId/:blockId",
    routeModule:
      "app/routes/api+/inbound-ivr/$numberId/$pageId/$blockId.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "ivr",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
];
