/**
 * Internal/session API surface entries — part 2 of 2.
 * Positional split for the app file-size gate (#1048): entry ORDER feeds the
 * generated inventory/OpenAPI output and must be preserved across the parts.
 */
import type { ApiSurfaceEntry } from "@/lib/api-surface-types";
import { GUIDE, seed } from "@/lib/api-surface-seeds";

export const INTERNAL_API_SURFACE_2: readonly ApiSurfaceEntry[] = [
  seed({
    path: "/api/inbound-ivr/:numberId/:pageId/:blockId/response",
    routeModule:
      "app/routes/api+/inbound-ivr/$numberId/$pageId/$blockId/response.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "ivr",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/inbound-queue",
    routeModule: "app/routes/api+/inbound-queue.tsx",
    authClass: "session",
    ownerArea: "inbound",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "json" },
      { method: "PUT", handler: "action", bodyType: "json" },
      { method: "PATCH", handler: "action", bodyType: "json" },
      { method: "DELETE", handler: "action", bodyType: "json" },
    ],
  }),
  seed({
    path: "/api/inbound-sms",
    routeModule: "app/routes/api+/inbound-sms.tsx",
    authClass: "twilioSignature",
    ownerArea: "messaging",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/inbound-verification",
    routeModule: "app/routes/api+/inbound-verification.tsx",
    authClass: "internalTrusted",
    ownerArea: "inbound",
    exposure: "internalOnly",
    docsGuide: GUIDE.internal,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
    securityWarning: "Call-in verification TwiML; validated with main-account Twilio signature.",
    notes: "Returns TwiML.",
  }),
  seed({
    path: "/api/inbound",
    routeModule: "app/routes/api+/inbound.tsx",
    authClass: "twilioSignature",
    ownerArea: "inbound",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
    notes: "Returns TwiML.",
  }),
  seed({
    path: "/api/jobs/low-credit-notify",
    routeModule: "app/routes/api+/jobs+/low-credit-notify.tsx",
    authClass: "internalTrusted",
    ownerArea: "billing",
    exposure: "internalOnly",
    docsGuide: GUIDE.internal,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
    notes:
      "Cron-triggered low-credit email sweep; authenticated via x-cron-secret header (process.env.CRON_SECRET).",
  }),
  seed({
    path: "/api/jobs/number-rental-billing",
    routeModule: "app/routes/api+/jobs+/number-rental-billing.tsx",
    authClass: "internalTrusted",
    ownerArea: "billing",
    exposure: "internalOnly",
    docsGuide: GUIDE.internal,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
    notes:
      "Cron-triggered monthly number-rental billing; authenticated via x-cron-secret header (process.env.CRON_SECRET).",
  }),
  seed({
    path: "/api/jobs/billing-reconcile",
    routeModule: "app/routes/api+/jobs+/billing-reconcile.tsx",
    authClass: "internalTrusted",
    ownerArea: "billing",
    exposure: "internalOnly",
    docsGuide: GUIDE.internal,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
    notes:
      "Cron-triggered billing reconciliation snapshot; authenticated via x-cron-secret header (process.env.CRON_SECRET).",
  }),
  seed({
    path: "/api/jobs/twilio-open-sync",
    routeModule: "app/routes/api+/jobs+/twilio-open-sync.tsx",
    authClass: "internalTrusted",
    ownerArea: "telephony",
    exposure: "internalOnly",
    docsGuide: GUIDE.internal,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
    notes:
      "Cron-triggered sync of open Twilio calls/messages; authenticated via x-cron-secret header (process.env.CRON_SECRET).",
  }),
  seed({
    path: "/api/initiate-ivr",
    routeModule: "app/routes/api+/initiate-ivr.tsx",
    authClass: "session",
    ownerArea: "ivr",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  seed({
    path: "/api/ivr",
    routeModule: "app/routes/api+/ivr.tsx",
    authClass: "session",
    ownerArea: "ivr",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/ivr/status",
    routeModule: "app/routes/api+/ivr/status.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "ivr",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/ivr/:campaignId/:pageId",
    routeModule: "app/routes/api+/ivr/$campaignId/$pageId.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "ivr",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
    notes: "Returns TwiML.",
  }),
  seed({
    path: "/api/ivr/:campaignId/:pageId/:blockId",
    routeModule: "app/routes/api+/ivr/$campaignId/$pageId/$blockId.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "ivr",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/ivr/:campaignId/:pageId/:blockId/response",
    routeModule:
      "app/routes/api+/ivr/$campaignId/$pageId/$blockId/response.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "ivr",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/media",
    routeModule: "app/routes/api+/media.tsx",
    authClass: "session",
    ownerArea: "media",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [{ method: "POST", handler: "action", bodyType: "multipart" }],
  }),
  seed({
    path: "/api/message_media",
    routeModule: "app/routes/api+/message_media.tsx",
    authClass: "session",
    ownerArea: "messaging",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [
      { method: "POST", handler: "action", bodyType: "multipart" },
      { method: "DELETE", handler: "action", bodyType: "form" },
    ],
  }),
  seed({
    path: "/api/numbers",
    routeModule: "app/routes/api+/numbers.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.workspace,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "form" },
    ],
  }),
  seed({
    path: "/api/outreach-attempts",
    routeModule: "app/routes/api+/outreach-attempts.tsx",
    authClass: "session",
    ownerArea: "campaigns",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
    notes: "Hyphenated path; preferred outreach attempt API.",
  }),
  seed({
    path: "/api/outreach_attempts/:id",
    routeModule: "app/routes/api+/outreach_attempts/$id.route.tsx",
    authClass: "session",
    ownerArea: "campaigns",
    exposure: "internalOnly",
    docsGuide: GUIDE.internal,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
    notes: "Session-scoped outreach attempt updates via requireJsonAuthForOutreachAttempt.",
  }),
  seed({
    path: "/api/questions",
    routeModule: "app/routes/api+/questions.tsx",
    authClass: "session",
    ownerArea: "campaigns",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
    notes: "Call disposition / survey question updates on call screen.",
  }),
  seed({
    path: "/api/queues",
    routeModule: "app/routes/api+/queues.tsx",
    authClass: "session",
    ownerArea: "queues",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "json" },
      { method: "DELETE", handler: "action", bodyType: "json" },
    ],
    notes: "Campaign queue dequeue and reset; requires session auth and workspace access.",
  }),
  seed({
    path: "/api/recording",
    routeModule: "app/routes/api+/recording.tsx",
    authClass: "twilioSignature",
    ownerArea: "telephony",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/reset_campaign",
    routeModule: "app/routes/api+/reset_campaign.tsx",
    authClass: "session",
    ownerArea: "campaigns",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/scripts",
    routeModule: "app/routes/api+/scripts.tsx",
    authClass: "session",
    ownerArea: "scripts",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  seed({
    path: "/api/sms",
    routeModule: "app/routes/api+/sms.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "messaging",
    exposure: "publicSdk",
    docsGuide: "docs/api-send-sms.md",
    workspaceScoped: true,
    operations: [
      {
        method: "POST",
        handler: "action",
        bodyType: "json",
        capability: "campaigns.dispatch",
      },
    ],
  }),
  seed({
    path: "/api/sms/status",
    routeModule: "app/routes/api+/sms/status.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "messaging",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/stripe-webhook",
    routeModule: "app/routes/api+/stripe-webhook.tsx",
    authClass: "stripeSignature",
    ownerArea: "billing",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "rawWebhook" }],
    notes: "Stripe-Signature header required; see docs/stripe-webhook.md.",
  }),
  seed({
    path: "/api/survey-answer",
    routeModule: "app/routes/api+/survey-answer.tsx",
    authClass: "publicForm",
    ownerArea: "surveys",
    exposure: "publicUnauthenticated",
    docsGuide: GUIDE.internal,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
    notes: "Public survey respondent flow.",
  }),
  seed({
    path: "/api/survey-complete",
    routeModule: "app/routes/api+/survey-complete.tsx",
    authClass: "publicForm",
    ownerArea: "surveys",
    exposure: "publicUnauthenticated",
    docsGuide: GUIDE.internal,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/survey-responses",
    routeModule: "app/routes/api+/survey-responses.tsx",
    authClass: "session",
    ownerArea: "surveys",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
  }),
  seed({
    path: "/api/surveys",
    routeModule: "app/routes/api+/surveys.tsx",
    authClass: "session",
    ownerArea: "surveys",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [
      { method: "POST", handler: "action", bodyType: "json" },
      { method: "PATCH", handler: "action", bodyType: "json" },
      { method: "DELETE", handler: "action", bodyType: "json" },
    ],
  }),
  seed({
    path: "/api/test-webhook",
    routeModule: "app/routes/api+/test-webhook.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "workspace",
    exposure: "sessionOnly",
    docsGuide: GUIDE.workspace,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  seed({
    path: "/api/token",
    routeModule: "app/routes/api+/token.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
    notes: "Twilio client access token for browser dialer.",
  }),
  seed({
    path: "/api/verify-audio-pin/:pin",
    routeModule: "app/routes/api+/verify-audio-pin/$pin.route.tsx",
    authClass: "publicForm",
    ownerArea: "telephony",
    exposure: "publicUnauthenticated",
    docsGuide: GUIDE.internal,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
    notes: "Retired audio PIN flow; returns 410.",
  }),
  seed({
    path: "/api/verify-audio-session",
    routeModule: "app/routes/api+/verify-audio-session.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "form" },
    ],
    notes: "Retired audio PIN flow; both methods return 410.",
  }),
  seed({
    path: "/api/verify-call-in-session",
    routeModule: "app/routes/api+/verify-call-in-session.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  seed({
    path: "/api/verify-pin-input",
    routeModule: "app/routes/api+/verify-pin-input.tsx",
    authClass: "internalTrusted",
    ownerArea: "telephony",
    exposure: "internalOnly",
    docsGuide: GUIDE.internal,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
    notes: "Retired audio PIN flow; returns 410.",
  }),
  seed({
    path: "/api/workspace-api-keys",
    routeModule: "app/routes/api+/workspace-api-keys.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "workspace",
    exposure: "sessionOnly",
    docsGuide: GUIDE.workspace,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "json" },
      { method: "DELETE", handler: "action", bodyType: "json" },
    ],
  }),
  seed({
    path: "/api/twilio/trusthub/status",
    routeModule: "app/routes/api+/twilio/trusthub/status.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "messaging",
    exposure: "providerOnly",
    docsGuide: GUIDE.webhooks,
    operations: [{ method: "POST", handler: "action", bodyType: "form" }],
    notes:
      "Trust Hub status_callback receiver; resolves workspace by customer-profile bundle SID and reconciles compliance status.",
  }),
  seed({
    path: "/api/twilio/a2p/events",
    routeModule: "app/routes/api+/twilio/a2p/events.route.tsx",
    authClass: "internalTrusted",
    ownerArea: "messaging",
    exposure: "internalOnly",
    docsGuide: GUIDE.internal,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
    notes:
      "A2P Event Streams sink receiver (JSON body), gated by the TWILIO_EVENTS_SINK_SECRET shared secret (?token=… on the sink URL). Parses brand/campaign lifecycle events and reconciles workspace onboarding status.",
  }),
];
