/**
 * Platform API surface entries — part 2 of 2 (see api-surface-platform.ts).
 * Positional split for the app file-size gate (#1048); order preserved.
 */
import type { ApiSurfaceEntry } from "@/lib/api-surface-types";
import { PLATFORM_GUIDE as GUIDE, platformSeed } from "@/lib/api-surface-seeds";

export const PLATFORM_API_SURFACE_2: readonly ApiSurfaceEntry[] = [
  platformSeed({
    path: "/api/contacts/:contactId",
    routeModule: "app/routes/api+/contacts/$contactId.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "contacts",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [
      {
        method: "GET",
        handler: "loader",
        bodyType: "query",
        capability: "campaigns.read",
      },
      {
        method: "DELETE",
        handler: "action",
        bodyType: "json",
        capability: "campaigns.write",
      },
    ],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/audiences",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/audiences.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "audiences",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    workspaceScoped: true,
    operations: [{
        method: "GET",
        handler: "loader",
        bodyType: "query",
        capability: "campaigns.read",
      }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/audiences/:audienceId",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/audiences/$audienceId.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "audiences",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    workspaceScoped: true,
    operations: [{
        method: "GET",
        handler: "loader",
        bodyType: "query",
        capability: "campaigns.read",
      }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/audience-uploads/:uploadId",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/audience-uploads/$uploadId.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "audiences",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    workspaceScoped: true,
    operations: [{
        method: "GET",
        handler: "loader",
        bodyType: "query",
        capability: "campaigns.read",
      }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/scripts",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/scripts.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "scripts",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    workspaceScoped: true,
    operations: [{
        method: "GET",
        handler: "loader",
        bodyType: "query",
        capability: "campaigns.read",
      }],
  }),
  platformSeed({
    path: "/api/scripts/:scriptId",
    routeModule: "app/routes/api+/scripts/$scriptId.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "scripts",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [{
        method: "GET",
        handler: "loader",
        bodyType: "query",
        capability: "campaigns.read",
      }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/surveys",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/surveys.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "surveys",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    workspaceScoped: true,
    operations: [{
        method: "GET",
        handler: "loader",
        bodyType: "query",
        capability: "campaigns.read",
      }],
  }),
  platformSeed({
    path: "/api/surveys/:surveyId",
    routeModule: "app/routes/api+/surveys/$surveyId.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "surveys",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [{
        method: "GET",
        handler: "loader",
        bodyType: "query",
        capability: "campaigns.read",
      }],
  }),
  platformSeed({
    path: "/api/surveys/:surveyId/responses",
    routeModule: "app/routes/api+/surveys/$surveyId/responses.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "surveys",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [{
        method: "GET",
        handler: "loader",
        bodyType: "query",
        capability: "campaigns.read",
      }],
  }),
  platformSeed({
    path: "/api/surveys/:surveyId/responses/export",
    routeModule:
      "app/routes/api+/surveys+/$surveyId/responses/export.route.tsx",
    authClass: "session",
    ownerArea: "analytics",
    exposure: "sessionOnly",
    docsGuide: GUIDE.analytics,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/conversations",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/conversations.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "messaging",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    workspaceScoped: true,
    operations: [{
        method: "GET",
        handler: "loader",
        bodyType: "query",
        capability: "campaigns.read",
      }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/conversations/:contactNumber",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/conversations/$contactNumber.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "messaging",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    workspaceScoped: true,
    operations: [{
        method: "GET",
        handler: "loader",
        bodyType: "query",
        capability: "campaigns.read",
      }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/audios",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/audios.route.tsx",
    authClass: "session",
    ownerArea: "media",
    exposure: "sessionOnly",
    docsGuide: GUIDE.analytics,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "multipart" },
    ],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/voicemails",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/voicemails.route.tsx",
    authClass: "session",
    ownerArea: "media",
    exposure: "sessionOnly",
    docsGuide: GUIDE.analytics,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/analytics",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/analytics.route.tsx",
    authClass: "session",
    ownerArea: "analytics",
    exposure: "sessionOnly",
    docsGuide: GUIDE.analytics,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/exports",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/exports.route.tsx",
    authClass: "session",
    ownerArea: "analytics",
    exposure: "sessionOnly",
    docsGuide: GUIDE.analytics,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/calls",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/calls.route.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.live,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/calls/listening",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/calls/listening.route.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.live,
    workspaceScoped: true,
    operations: [
      { method: "POST", handler: "action", bodyType: "json" },
      { method: "DELETE", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/calls/:callSid/disconnect",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/calls/$callSid/disconnect.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [{
        method: "POST",
        handler: "action",
        bodyType: "json",
        capability: "calls.control",
      }],
    notes: "Workspace-scoped call disconnect using workspace Twilio credentials. Capability: calls.control.",
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/campaigns/:campaignId/dialer/start",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/campaigns/$campaignId/dialer/start.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "dialer",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [{
        method: "POST",
        handler: "action",
        bodyType: "json",
        capability: "calls.start",
      }],
    notes: "Start predictive/manual auto-dial conference for authenticated caller+ agent. Capability: calls.start.",
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/handset/session",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/handset/session.route.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.live,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "DELETE", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/admin/dashboard",
    routeModule: "app/routes/api+/admin+/dashboard.route.tsx",
    authClass: "internalTrusted",
    ownerArea: "misc",
    exposure: "internalOnly",
    docsGuide: GUIDE.admin,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "json" },
    ],
    notes: "Sudo-only admin dashboard and actions.",
  }),
  platformSeed({
    path: "/api/admin/users/:userId",
    routeModule: "app/routes/api+/admin+/users+/$userId.route.tsx",
    authClass: "internalTrusted",
    ownerArea: "misc",
    exposure: "internalOnly",
    docsGuide: GUIDE.admin,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "PATCH", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/admin/users/:userId/workspaces",
    routeModule: "app/routes/api+/admin+/users+/$userId/workspaces.route.tsx",
    authClass: "internalTrusted",
    ownerArea: "misc",
    exposure: "internalOnly",
    docsGuide: GUIDE.admin,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/admin/workspaces/:workspaceId/twilio",
    routeModule:
      "app/routes/api+/admin+/workspaces+/$workspaceId/twilio.route.tsx",
    authClass: "internalTrusted",
    ownerArea: "misc",
    exposure: "internalOnly",
    docsGuide: GUIDE.admin,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  platformSeed({
    path: "/api/auth/*",
    routeModule: "app/routes/api+/auth/$.route.tsx",
    authClass: "publicForm",
    ownerArea: "auth",
    exposure: "publicUnauthenticated",
    docsGuide: GUIDE.auth,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "json" },
    ],
    notes:
      "Better Auth catch-all (sign-in, session, sign-out, OAuth callbacks). POSTs are rate-limited: sign-in/two-factor 10/min per IP, other POSTs 30/min.",
  }),
  platformSeed({
    path: "/api/acd-router",
    routeModule: "app/routes/api+/acd-router.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "telephony",
    exposure: "internalOnly",
    docsGuide: GUIDE.live,
    operations: [{ method: "POST", handler: "action", bodyType: "twiml" }],
    notes: "Twilio ACD wait URL.",
  }),
  platformSeed({
    path: "/api/acd-router/agent-bridge",
    routeModule: "app/routes/api+/acd-router/agent-bridge.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "telephony",
    exposure: "internalOnly",
    docsGuide: GUIDE.live,
    operations: [{ method: "POST", handler: "action", bodyType: "twiml" }],
  }),
  platformSeed({
    path: "/api/acd-router/agent-status",
    routeModule: "app/routes/api+/acd-router/agent-status.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "telephony",
    exposure: "internalOnly",
    docsGuide: GUIDE.live,
    operations: [{ method: "POST", handler: "action", bodyType: "twiml" }],
  }),
  platformSeed({
    path: "/api/acd-router/complete",
    routeModule: "app/routes/api+/acd-router/complete.route.tsx",
    authClass: "twilioSignature",
    ownerArea: "telephony",
    exposure: "internalOnly",
    docsGuide: GUIDE.live,
    operations: [{ method: "POST", handler: "action", bodyType: "twiml" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/audiences/:audienceId/uploads",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/audiences/$audienceId/uploads.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "audiences",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    workspaceScoped: true,
    operations: [{
        method: "GET",
        handler: "loader",
        bodyType: "query",
        capability: "campaigns.read",
      }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/events",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/events.route.tsx",
    authClass: "session",
    ownerArea: "misc",
    exposure: "sessionOnly",
    docsGuide: GUIDE.live,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
    notes: "SSE stream for workspace events (activity log).",
  }),
];
