import type { ApiSurfaceEntry } from "@/lib/api-surface-types";

type Op = {
  method: "GET" | "POST" | "PATCH" | "PUT" | "DELETE";
  handler: "loader" | "action";
  bodyType: "json" | "query" | "form" | "multipart" | "twiml" | "rawWebhook";
};

type PlatformSeed = {
  path: string;
  routeModule: string;
  authClass: ApiSurfaceEntry["authClass"];
  ownerArea: ApiSurfaceEntry["ownerArea"];
  exposure: ApiSurfaceEntry["exposure"];
  docsGuide: string;
  operations: Op[];
  notes?: string;
  workspaceScoped?: boolean;
};

function platformSeed(input: PlatformSeed): ApiSurfaceEntry {
  return {
    path: input.path,
    routeModule: input.routeModule,
    authClass: input.authClass,
    ownerArea: input.ownerArea,
    exposure: input.exposure,
    supported: true,
    specTarget: "publicOpenApi",
    docsGuide: input.docsGuide,
    operations: input.operations,
    notes: input.notes,
    workspaceScoped: input.workspaceScoped,
  };
}

const GUIDE = {
  auth: "docs/api-auth-matrix.md",
  platform: "docs/api-agent-quickstart.md",
  workspace: "docs/api-workspace-admin.md",
  data: "docs/api-data-plane.md",
  analytics: "docs/api-analytics-export.md",
  telephony: "docs/api-telephony-provisioning.md",
  live: "docs/api-live-operations.md",
  admin: "docs/api-admin.md",
} as const;

/** Platform / agent-friendly CaaS routes added for full API parity. */
export const PLATFORM_API_SURFACE: readonly ApiSurfaceEntry[] = [
  platformSeed({
    path: "/api/auth/register",
    routeModule: "app/routes/api+/auth/register.route.tsx",
    authClass: "publicForm",
    ownerArea: "auth",
    exposure: "publicUnauthenticated",
    docsGuide: GUIDE.platform,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  platformSeed({
    path: "/api/auth/token",
    routeModule: "app/routes/api+/auth/token.route.tsx",
    authClass: "publicForm",
    ownerArea: "auth",
    exposure: "publicUnauthenticated",
    docsGuide: GUIDE.platform,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  platformSeed({
    path: "/api/auth/refresh",
    routeModule: "app/routes/api+/auth/refresh.route.tsx",
    authClass: "publicForm",
    ownerArea: "auth",
    exposure: "publicUnauthenticated",
    docsGuide: GUIDE.platform,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  platformSeed({
    path: "/api/auth/signout",
    routeModule: "app/routes/api+/auth/signout.route.tsx",
    authClass: "session",
    ownerArea: "auth",
    exposure: "sessionOnly",
    docsGuide: GUIDE.platform,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  platformSeed({
    path: "/api/auth/forgot-password",
    routeModule: "app/routes/api+/auth/forgot-password.route.tsx",
    authClass: "publicForm",
    ownerArea: "auth",
    exposure: "publicUnauthenticated",
    docsGuide: GUIDE.platform,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  platformSeed({
    path: "/api/auth/reset-password",
    routeModule: "app/routes/api+/auth/reset-password.route.tsx",
    authClass: "session",
    ownerArea: "auth",
    exposure: "sessionOnly",
    docsGuide: GUIDE.platform,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  platformSeed({
    path: "/api/auth/verify-email",
    routeModule: "app/routes/api+/auth/verify-email.route.tsx",
    authClass: "publicForm",
    ownerArea: "auth",
    exposure: "publicUnauthenticated",
    docsGuide: GUIDE.platform,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  platformSeed({
    path: "/api/auth/invites",
    routeModule: "app/routes/api+/auth/invites.route.tsx",
    authClass: "session",
    ownerArea: "auth",
    exposure: "sessionOnly",
    docsGuide: GUIDE.platform,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/me",
    routeModule: "app/routes/api+/me.route.tsx",
    authClass: "session",
    ownerArea: "auth",
    exposure: "sessionOnly",
    docsGuide: GUIDE.platform,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "PATCH", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/workspaces",
    routeModule: "app/routes/api+/workspaces.route.tsx",
    authClass: "session",
    ownerArea: "workspace",
    exposure: "sessionOnly",
    docsGuide: GUIDE.platform,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId",
    routeModule: "app/routes/api+/workspaces+/$workspaceId.route.tsx",
    authClass: "session",
    ownerArea: "workspace",
    exposure: "sessionOnly",
    docsGuide: GUIDE.platform,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "PATCH", handler: "action", bodyType: "json" },
      { method: "DELETE", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/transfer-ownership",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/transfer-ownership.route.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "workspace",
    exposure: "sessionOnly",
    docsGuide: GUIDE.workspace,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/billing",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/billing.route.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "billing",
    exposure: "sessionOnly",
    docsGuide: GUIDE.platform,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/billing/checkout-session",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/billing/checkout-session.route.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "billing",
    exposure: "sessionOnly",
    docsGuide: GUIDE.platform,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/billing/sessions/:sessionId",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/billing/sessions/$sessionId.route.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "billing",
    exposure: "sessionOnly",
    docsGuide: GUIDE.platform,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/onboarding",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/onboarding.route.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "PATCH", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/onboarding/actions",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/onboarding/actions.route.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/numbers",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/numbers.route.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/numbers/:numberId",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/numbers/$numberId.route.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.telephony,
    workspaceScoped: true,
    operations: [
      { method: "PATCH", handler: "action", bodyType: "json" },
      { method: "DELETE", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/webhook",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/webhook.route.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "workspace",
    exposure: "sessionOnly",
    docsGuide: GUIDE.workspace,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "PUT", handler: "action", bodyType: "json" },
      { method: "POST", handler: "action", bodyType: "json" },
    ],
    notes: "POST tests webhook delivery.",
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/members",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/members.route.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "workspace",
    exposure: "sessionOnly",
    docsGuide: GUIDE.workspace,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "json" },
      { method: "PATCH", handler: "action", bodyType: "json" },
      { method: "DELETE", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/api-keys",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/api-keys.route.tsx",
    authClass: "workspaceAdmin",
    ownerArea: "workspace",
    exposure: "sessionOnly",
    docsGuide: GUIDE.workspace,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "json" },
      { method: "DELETE", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/campaigns",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/campaigns.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "campaigns",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/campaigns/:campaignId",
    routeModule: "app/routes/api+/campaigns/$campaignId.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "campaigns",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/campaigns/:campaignId/queue",
    routeModule: "app/routes/api+/campaigns/$campaignId/queue.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "campaigns",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "PATCH", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/campaigns/:campaignId/results",
    routeModule: "app/routes/api+/campaigns+/$campaignId/results.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "analytics",
    exposure: "sessionOnly",
    docsGuide: GUIDE.analytics,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/campaigns/:campaignId/call-session",
    routeModule: "app/routes/api+/campaigns+/$campaignId/call-session.route.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.live,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/campaigns/:campaignId/call-session/release",
    routeModule:
      "app/routes/api+/campaigns+/$campaignId/call-session/release.route.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.live,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/contacts",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/contacts.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "contacts",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/contacts/:contactId",
    routeModule: "app/routes/api+/contacts/$contactId.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "contacts",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "DELETE", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/audiences",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/audiences.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "audiences",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/audiences/:audienceId",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/audiences/$audienceId.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "audiences",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/audience-uploads/:uploadId",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/audience-uploads/$uploadId.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "audiences",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/scripts",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/scripts.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "scripts",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/scripts/:scriptId",
    routeModule: "app/routes/api+/scripts/$scriptId.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "scripts",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/surveys",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/surveys.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "surveys",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/surveys/:surveyId",
    routeModule: "app/routes/api+/surveys/$surveyId.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "surveys",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/surveys/:surveyId/responses",
    routeModule: "app/routes/api+/surveys/$surveyId/responses.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "surveys",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/surveys/:surveyId/responses/export",
    routeModule:
      "app/routes/api+/surveys+/$surveyId/responses/export.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "analytics",
    exposure: "sessionOnly",
    docsGuide: GUIDE.analytics,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/conversations",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/conversations.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "messaging",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/conversations/:contactNumber",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/conversations/$contactNumber.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "messaging",
    exposure: "sessionOnly",
    docsGuide: GUIDE.data,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/audios",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/audios.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "media",
    exposure: "sessionOnly",
    docsGuide: GUIDE.analytics,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "multipart" },
    ],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/voicemails",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/voicemails.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "media",
    exposure: "sessionOnly",
    docsGuide: GUIDE.analytics,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/analytics",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/analytics.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "analytics",
    exposure: "sessionOnly",
    docsGuide: GUIDE.analytics,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/exports",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/exports.route.tsx",
    authClass: "apiKeyOrSession",
    ownerArea: "analytics",
    exposure: "sessionOnly",
    docsGuide: GUIDE.analytics,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/calls",
    routeModule: "app/routes/api+/workspaces+/$workspaceId/calls.route.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.live,
    workspaceScoped: true,
    operations: [{ method: "GET", handler: "loader", bodyType: "query" }],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/calls/listening",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/calls/listening.route.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.live,
    workspaceScoped: true,
    operations: [
      { method: "POST", handler: "action", bodyType: "json" },
      { method: "DELETE", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/workspaces/:workspaceId/handset/session",
    routeModule:
      "app/routes/api+/workspaces+/$workspaceId/handset/session.route.tsx",
    authClass: "session",
    ownerArea: "telephony",
    exposure: "sessionOnly",
    docsGuide: GUIDE.live,
    workspaceScoped: true,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "DELETE", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/admin/dashboard",
    routeModule: "app/routes/api+/admin+/dashboard.route.tsx",
    authClass: "internalTrusted",
    ownerArea: "misc",
    exposure: "internalOnly",
    docsGuide: GUIDE.admin,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "json" },
    ],
    notes: "Sudo-only admin dashboard and actions.",
  }),
  platformSeed({
    path: "/api/admin/users/:userId",
    routeModule: "app/routes/api+/admin+/users+/$userId.route.tsx",
    authClass: "internalTrusted",
    ownerArea: "misc",
    exposure: "internalOnly",
    docsGuide: GUIDE.admin,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "PATCH", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/admin/users/:userId/workspaces",
    routeModule: "app/routes/api+/admin+/users+/$userId/workspaces.route.tsx",
    authClass: "internalTrusted",
    ownerArea: "misc",
    exposure: "internalOnly",
    docsGuide: GUIDE.admin,
    operations: [
      { method: "GET", handler: "loader", bodyType: "query" },
      { method: "POST", handler: "action", bodyType: "json" },
    ],
  }),
  platformSeed({
    path: "/api/admin/workspaces/:workspaceId/twilio",
    routeModule:
      "app/routes/api+/admin+/workspaces+/$workspaceId/twilio.route.tsx",
    authClass: "internalTrusted",
    ownerArea: "misc",
    exposure: "internalOnly",
    docsGuide: GUIDE.admin,
    operations: [{ method: "POST", handler: "action", bodyType: "json" }],
  }),
];
