import type { Audience, Contact, ContactAudience } from "@/lib/types";

export const saved: Contact & { contact_audience: ContactAudience[] } = {
  id: 5,
  firstname: "Original",
  surname: "Name",
  phone: "+15555550123",
  email: null,
  address: null,
  city: null,
  country: null,
  created_at: "2026-10-07",
  created_by: null,
  date_updated: null,
  external_id: null,
  household_id: null,
  line_type: null,
  line_type_checked_at: null,
  opt_out: false,
  postal: null,
  province: null,
  support_level: null,
  voter_id: null,
  voter_list_expires_at: null,
  voter_list_imported_at: null,
  voter_list_source: null,
  workspace: "owned-workspace",
  other_data: [
    { notes: "VIP", hidden: { enabled: true, count: 3 } },
    { score: 7 },
    null,
  ],
  contact_audience: [1, 99].map((audience_id) => ({
    audience_id,
    contact_id: 5,
    created_at: "2026-10-07",
  })),
};
export const audiences: Audience[] = [1, 2].map((id) => ({
  id,
  name: `List ${id}`,
  workspace: "owned-workspace",
  created_at: "2026-10-07",
  is_conditional: false,
  status: "pending",
  total_contacts: null,
  processed_contacts: null,
  processed_at: null,
  error_message: null,
}));
