FROM oven/bun:1.2-bookworm-slim
WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile --production

COPY app ./app
COPY shared ./shared
COPY worker ./worker

ENV NODE_ENV=production

CMD ["bun", "worker/index.ts"]
