// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { CreateCampaignWithScriptData, CreateCampaignWithScriptResponse2, CreateCampaignWithScriptError, SendChatSmsData, SendChatSmsResponse, SendChatSmsError, DispatchCampaignSmsData, DispatchCampaignSmsResponse, DispatchCampaignSmsError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Create campaign with script and phone number (one-shot)
 * Creates a call campaign in a single request: optionally creates a script, creates the campaign with a caller ID, and attaches audiences (with optional contact enqueue). Provide exactly one of `script` or `script_id`, not both.
 */
export const createCampaignWithScript = <ThrowOnError extends boolean = false>(options: Options<CreateCampaignWithScriptData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateCampaignWithScriptResponse2, CreateCampaignWithScriptError, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sb-access-token',
                type: 'apiKey'
            },
            {
                name: 'X-API-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/campaigns/create-with-script',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Send a single SMS
 * Sends one outbound SMS to a phone number. When `contact_id` is provided, template tags in `body` are substituted from the contact record. Session auth requires `workspace_id` in the body.
 */
export const sendChatSms = <ThrowOnError extends boolean = false>(options: Options<SendChatSmsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<SendChatSmsResponse, SendChatSmsError, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sb-access-token',
                type: 'apiKey'
            },
            {
                name: 'X-API-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/chat_sms',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Dispatch SMS to queued campaign contacts
 * Legacy batch dispatch: sends SMS to all queued contacts on a message campaign. Processes template tags per contact. Duplicate sends to the same number are skipped and the queue row is dequeued. API key auth requires `user_id` for outreach attribution; session auth uses the logged-in user.
 */
export const dispatchCampaignSms = <ThrowOnError extends boolean = false>(options: Options<DispatchCampaignSmsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<DispatchCampaignSmsResponse, DispatchCampaignSmsError, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sb-access-token',
                type: 'apiKey'
            },
            {
                name: 'X-API-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/sms',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};