// This file is auto-generated by @hey-api/openapi-ts

export type _Error = {
    error: string;
};

/**
 * Required in the request body when using session auth. Optional with API key; must match the key workspace if provided.
 */
export type WorkspaceId = string;

/**
 * Provide exactly one of `script` or `script_id` (XOR). Enforced in Zod validation, not in OpenAPI required fields.
 */
export type CreateCampaignWithScriptRequest = {
    workspace_id?: WorkspaceId;
    /**
     * Campaign title.
     */
    title: string;
    /**
     * Campaign type (script-based).
     */
    type: 'live_call' | 'robocall' | 'simple_ivr' | 'complex_ivr';
    /**
     * Outbound caller ID. Must be a workspace phone number (e.g. +15551234567).
     */
    caller_id: string;
    /**
     * Inline script to create and attach. Use this OR script_id.
     */
    script?: {
        /**
         * Script display name.
         */
        name: string;
        /**
         * script for live_call, ivr for IVR types. Defaults from campaign type.
         */
        type?: 'script' | 'ivr';
        /**
         * Script content (pages, blocks). See docs/script-json-format.md.
         */
        steps?: {
            [key: string]: unknown;
        };
    };
    /**
     * ID of an existing script to attach. Use this OR script.
     */
    script_id?: number;
    /**
     * Audience IDs to attach (must belong to workspace).
     */
    audience_ids?: Array<number>;
    /**
     * If true, enqueue contacts from attached audiences; if false, only link audiences.
     */
    enqueue_audience_contacts?: boolean;
    /**
     * Campaign status (e.g. draft, active).
     */
    status?: string;
    is_active?: boolean;
    start_date?: string | null;
    end_date?: string | null;
    schedule?: {
        [key: string]: unknown;
    };
};

export type CreateCampaignWithScriptResponse = {
    /**
     * Created campaign row (id, title, workspace, type, caller_id, status, ...).
     */
    campaign?: {
        [key: string]: unknown;
    };
    /**
     * Type-specific details (e.g. live_campaign/ivr_campaign) with campaign_id, script_id.
     */
    campaignDetails?: {
        [key: string]: unknown;
    };
    /**
     * Present only when a script was created in this request.
     */
    script?: {
        id?: number;
        name?: string;
        type?: string | null;
        steps?: {
            [key: string]: unknown;
        };
    };
    /**
     * Number of campaign–audience links created.
     */
    audiences_linked?: number;
    /**
     * Total contacts added to the campaign queue.
     */
    contacts_enqueued?: number;
};

/**
 * Session auth requires workspace_id in the body.
 */
export type ChatSmsRequest = {
    workspace_id: WorkspaceId;
    /**
     * Recipient phone number (E.164 recommended).
     */
    to_number: string;
    /**
     * Workspace outbound caller ID.
     */
    caller_id: string;
    /**
     * SMS message body.
     */
    body: string;
    /**
     * Optional contact ID for template tag substitution.
     */
    contact_id?: string;
    /**
     * Optional media URL or path for MMS.
     */
    media?: string;
    /**
     * Twilio message intent (e.g. marketing, utility).
     */
    message_intent?: string;
    /**
     * Optional Twilio Messaging Service SID override.
     */
    messaging_service_sid?: string;
};

export type ChatSmsResponse = {
    data?: {
        [key: string]: unknown;
    };
    message?: {
        [key: string]: unknown;
    };
};

/**
 * Session auth requires workspace_id. API key auth requires user_id for outreach attribution.
 */
export type CampaignSmsDispatchRequest = {
    workspace_id: WorkspaceId;
    /**
     * Message campaign ID whose queued contacts receive SMS.
     */
    campaign_id: string;
    /**
     * Outbound caller ID. Required when campaign sms_send_mode requires it.
     */
    caller_id?: string;
    /**
     * Required when using API key auth (outreach attribution). Session auth uses the logged-in user.
     */
    user_id?: string;
    /**
     * Twilio message intent override.
     */
    message_intent?: string;
    /**
     * Twilio Messaging Service SID override.
     */
    messaging_service_sid?: string;
};

export type CampaignSmsDispatchResponse = {
    /**
     * Per-contact send results keyed by contact_id (success, skipped, or error).
     */
    responses?: Array<{
        [key: string]: unknown;
    }>;
};

export type CreateCampaignWithScriptData = {
    body: CreateCampaignWithScriptRequest;
    path?: never;
    query?: never;
    url: '/api/campaigns/create-with-script';
};

export type CreateCampaignWithScriptErrors = {
    /**
     * Validation or creation error
     */
    400: _Error;
    /**
     * Unauthorized (missing or invalid session / API key)
     */
    401: _Error;
    /**
     * Forbidden (e.g. workspace_id does not match API key)
     */
    403: _Error;
    /**
     * Method not allowed
     */
    405: _Error;
    /**
     * Server error
     */
    500: _Error;
};

export type CreateCampaignWithScriptError = CreateCampaignWithScriptErrors[keyof CreateCampaignWithScriptErrors];

export type CreateCampaignWithScriptResponses = {
    /**
     * Campaign created
     */
    201: CreateCampaignWithScriptResponse;
};

export type CreateCampaignWithScriptResponse2 = CreateCampaignWithScriptResponses[keyof CreateCampaignWithScriptResponses];

export type SendChatSmsData = {
    body: ChatSmsRequest;
    path?: never;
    query?: never;
    url: '/api/chat_sms';
};

export type SendChatSmsErrors = {
    /**
     * Validation error
     */
    400: _Error;
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden (workspace mismatch)
     */
    403: _Error;
    /**
     * Invalid phone number
     */
    404: _Error;
    /**
     * Send failure
     */
    500: _Error;
};

export type SendChatSmsError = SendChatSmsErrors[keyof SendChatSmsErrors];

export type SendChatSmsResponses = {
    /**
     * Message sent
     */
    201: ChatSmsResponse;
};

export type SendChatSmsResponse = SendChatSmsResponses[keyof SendChatSmsResponses];

export type DispatchCampaignSmsData = {
    body: CampaignSmsDispatchRequest;
    path?: never;
    query?: never;
    url: '/api/sms';
};

export type DispatchCampaignSmsErrors = {
    /**
     * Validation or campaign error
     */
    400: _Error;
    /**
     * Unauthorized
     */
    401: _Error;
    /**
     * Forbidden (workspace mismatch)
     */
    403: _Error;
    /**
     * Dispatch failure
     */
    500: _Error;
};

export type DispatchCampaignSmsError = DispatchCampaignSmsErrors[keyof DispatchCampaignSmsErrors];

export type DispatchCampaignSmsResponses = {
    /**
     * Batch dispatch completed
     */
    200: CampaignSmsDispatchResponse;
};

export type DispatchCampaignSmsResponse = DispatchCampaignSmsResponses[keyof DispatchCampaignSmsResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};