// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zError = z.object({
    error: z.string()
});

export const zWorkspaceId = z.string().uuid();

export const zCreateCampaignWithScriptRequest = z.object({
    workspace_id: zWorkspaceId.optional(),
    title: z.string(),
    type: z.enum([
        'live_call',
        'robocall',
        'simple_ivr',
        'complex_ivr'
    ]),
    caller_id: z.string(),
    script: z.object({
        name: z.string(),
        type: z.enum([
            'script',
            'ivr'
        ]).optional(),
        steps: z.object({}).optional()
    }).optional(),
    script_id: z.number().int().optional(),
    audience_ids: z.array(z.number().int()).optional(),
    enqueue_audience_contacts: z.boolean().optional().default(true),
    status: z.string().optional().default('draft'),
    is_active: z.boolean().optional(),
    start_date: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    end_date: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    schedule: z.object({}).optional()
});

export const zCreateCampaignWithScriptResponse = z.object({
    campaign: z.object({}).optional(),
    campaignDetails: z.object({}).optional(),
    script: z.object({
        id: z.number().int().optional(),
        name: z.string().optional(),
        type: z.union([
            z.string(),
            z.null()
        ]).optional(),
        steps: z.object({}).optional()
    }).optional(),
    audiences_linked: z.number().int().optional(),
    contacts_enqueued: z.number().int().optional()
});

export const zChatSmsRequest = z.object({
    workspace_id: zWorkspaceId,
    to_number: z.string(),
    caller_id: z.string(),
    body: z.string(),
    contact_id: z.string().optional(),
    media: z.string().optional(),
    message_intent: z.string().optional(),
    messaging_service_sid: z.string().optional()
});

export const zChatSmsResponse = z.object({
    data: z.object({}).optional(),
    message: z.object({}).optional()
});

export const zCampaignSmsDispatchRequest = z.object({
    workspace_id: zWorkspaceId,
    campaign_id: z.string(),
    caller_id: z.string().optional(),
    user_id: z.string().optional(),
    message_intent: z.string().optional(),
    messaging_service_sid: z.string().optional()
});

export const zCampaignSmsDispatchResponse = z.object({
    responses: z.array(z.object({})).optional()
});

export const zCreateCampaignWithScriptResponse2 = zCreateCampaignWithScriptResponse;

export const zSendChatSmsResponse = zChatSmsResponse;

export const zDispatchCampaignSmsResponse = zCampaignSmsDispatchResponse;